### ISSUE TITLE
JtR segfaults when using --show:left

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#1130]
On well. The hash file is in my ~.

```
$ ../run/john --show:left ~/testhashes
Warning: detected hash type "LM", but the string is also recognized as "HAVAL-128-4"
Use the "--format=HAVAL-128-4" option to force loading these as that type instead
Warning: detected hash type "LM", but the string is also recognized as "lotus5"
Use the "--format=lotus5" option to force loading these as that type instead
[...]
Segmentation fault (core dumped)
```

**Comment by claudioandre** [comment]
BTW: well has CUDA installed but no NVIDIA GPU. It is a bad idea. ./configure did its best and

```
Testing: md5crypt-cuda, crypt(3) $1$ [MD5 CUDA]... 
Error: No CUDA-capable devices were detected by the installed CUDA driver.
```

**Comment by magnumripper** [comment]
Yes, just use `./configure --disable-cuda --disable-native-tests` on that machine

**Comment by magnumripper** [comment]
```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x000000010024a96c in ldr_fix_database (db=0x100c538c0) at loader.c:1089
1089		if (!strncmp(pw_source, "$dynamic_", 9))
(gdb) bt
#0  0x000000010024a96c in ldr_fix_database (db=0x100c538c0) at loader.c:1089
#1  0x00000001002460bf in john_load () at john.c:1004
```

**Comment by magnumripper** [comment]
ASan does not catch any problem prior to this.
```
==46610==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010091020d sp 0x7fff5f72d6b0 bp 0x7fff5f72d820 T0)
    #0 0x10091020c in ldr_show_left loader.c:1089
    #1 0x1009108d3 in ldr_remove_marked loader.c:1136
    #2 0x100912c52 in ldr_fix_database loader.c:1376
    #3 0x100905427 in john_load john.c:1004
    #4 0x100906ce7 in john_init john.c:1241
    #5 0x100908fc5 in main john.c:1674
    #6 0x7fff8f1275c8 in start (in libdyld.dylib) + 0
    #7 0x3
```

**Comment by magnumripper** [comment]
OK here's a very simplified test case
```
$ cat file
8a9d093f14f8701d
f17732b2bb182c74
$ ../run/john file -form:lm --show=left
0 password hashes cracked, 0 left
```
```
$ cat file
8a9d093f14f8701df17732b2bb182c74
$ ../run/john file -form:lm --show=left
ASAN:SIGSEGV
```

**Comment by magnumripper** [comment]
For a while I though this was something about LM being split but it's not
```
$ ../run/john file -show=left -form:nt 
ASAN:SIGSEGV
```

**Comment by magnumripper** [comment]
This bug was introduced by f6af7d71d
