### ISSUE TITLE
memory leak in ssh format (get_salt)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1247]
```
$ valgrind --leak-check=full ../run/john --test=0 --format=ssh
```

produces several of these (which I didn't check so far, so it might be a false positive):
```
==16880== Conditional jump or move depends on uninitialised value(s)
==16880==    at 0x510DB4D: OPENSSL_cleanse (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5145E72: BN_clear_free (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x516526C: RSA_free (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B33B8: crypt_all (ssh_fmt_plug.c:421)
==16880==    by 0x5DDD1D: fmt_self_test_body (formats.c:541)
==16880==    by 0x5DDD1D: fmt_self_test (formats.c:691)
==16880==    by 0x5D2F24: benchmark_format.part.1 (bench.c:248)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
```

And these memory leaks:
```
==16880== HEAP SUMMARY:
==16880==     in use at exit: 161,304 bytes in 3,331 blocks
==16880==   total heap usage: 28,734 allocs, 25,403 frees, 5,371,558 bytes allocated
==16880== 
==16880== 3,632 (224 direct, 3,408 indirect) bytes in 2 blocks are definitely lost in loss record 619 of 630
==16880==    at 0x4C28C0F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16880==    by 0x510B3C7: CRYPTO_malloc (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x517A70E: BIO_new (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B2AC2: get_salt (ssh_fmt_plug.c:289)
==16880==    by 0x5D3198: benchmark_format.part.1 (bench.c:272)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
==16880== 
==16880== 15,220 (784 direct, 14,436 indirect) bytes in 7 blocks are definitely lost in loss record 626 of 630
==16880==    at 0x4C28C0F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16880==    by 0x510B3C7: CRYPTO_malloc (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x517A70E: BIO_new (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B2AC2: get_salt (ssh_fmt_plug.c:289)
==16880==    by 0x5DDB1C: fmt_self_test_body (formats.c:394)
==16880==    by 0x5DDB1C: fmt_self_test (formats.c:691)
==16880==    by 0x5D2F24: benchmark_format.part.1 (bench.c:248)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
==16880== 
==16880== 15,220 (784 direct, 14,436 indirect) bytes in 7 blocks are definitely lost in loss record 627 of 630
==16880==    at 0x4C28C0F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16880==    by 0x510B3C7: CRYPTO_malloc (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x517A70E: BIO_new (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B2AC2: get_salt (ssh_fmt_plug.c:289)
==16880==    by 0x5DE57F: fmt_self_test_body (formats.c:413)
==16880==    by 0x5DE57F: fmt_self_test (formats.c:691)
==16880==    by 0x5D2F24: benchmark_format.part.1 (bench.c:248)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
==16880== 
==16880== 15,220 (784 direct, 14,436 indirect) bytes in 7 blocks are definitely lost in loss record 628 of 630
==16880==    at 0x4C28C0F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16880==    by 0x510B3C7: CRYPTO_malloc (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x517A70E: BIO_new (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B2AC2: get_salt (ssh_fmt_plug.c:289)
==16880==    by 0x5DDBF2: fmt_self_test_body (formats.c:435)
==16880==    by 0x5DDBF2: fmt_self_test (formats.c:691)
==16880==    by 0x5D2F24: benchmark_format.part.1 (bench.c:248)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
==16880== 
==16880== 15,220 (784 direct, 14,436 indirect) bytes in 7 blocks are definitely lost in loss record 629 of 630
==16880==    at 0x4C28C0F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==16880==    by 0x510B3C7: CRYPTO_malloc (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x517A70E: BIO_new (in /usr/lib64/libcrypto.so.1.0.1k)
==16880==    by 0x5B2AC2: get_salt (ssh_fmt_plug.c:289)
==16880==    by 0x5DDC50: fmt_self_test_body (formats.c:470)
==16880==    by 0x5DDC50: fmt_self_test (formats.c:691)
==16880==    by 0x5D2F24: benchmark_format.part.1 (bench.c:248)
==16880==    by 0x5D3CC3: benchmark_all (bench.c:660)
==16880==    by 0x5E50EA: john_run (john.c:1319)
==16880==    by 0x5E5CD3: main (john.c:1697)
==16880== 
==16880== LEAK SUMMARY:
==16880==    definitely lost: 3,360 bytes in 30 blocks
==16880==    indirectly lost: 61,152 bytes in 60 blocks
==16880==      possibly lost: 0 bytes in 0 blocks
==16880==    still reachable: 96,792 bytes in 3,241 blocks
==16880==         suppressed: 0 bytes in 0 blocks
==16880== Reachable blocks (those to which a pointer was found) are not shown.
==16880== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==16880== 
==16880== For counts of detected and suppressed errors, rerun with: -v
==16880== Use --track-origins=yes to see where uninitialised values come from
==16880== ERROR SUMMARY: 8962 errors from 83 contexts (suppressed: 0 from 0)
```

**Comment by frank-dittrich** [comment]
BTW: ASAN just shows these 2 memleaks:
```
(bleeding-jumbo)run $ ./john --test=0 --format=ssh
Will run 8 OpenMP threads
Testing: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA 32/64]... (8xOMP) PASS

=================================================================
==6604==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 71672 byte(s) in 17 object(s) allocated from:
    #0 0x7fe0e9538a0a in malloc (/lib64/libasan.so.2+0x98a0a)
    #1 0x6ed586 in mem_alloc_func /home/fd/git/JtR/src/memory.c:89
    #2 0x6ed667 in mem_calloc_func /home/fd/git/JtR/src/memory.c:110
    #3 0x66b0f0 in get_salt /home/fd/git/JtR/src/ssh_fmt_plug.c:239
    #4 0x66ba2c in valid /home/fd/git/JtR/src/ssh_fmt_plug.c:365
    #5 0x6c25e1 in fmt_self_test_body /home/fd/git/JtR/src/formats.c:335
    #6 0x6c4e3f in fmt_self_test /home/fd/git/JtR/src/formats.c:719
    #7 0x6ac0c0 in benchmark_format /home/fd/git/JtR/src/bench.c:243
    #8 0x6adab1 in benchmark_all /home/fd/git/JtR/src/bench.c:661
    #9 0x6d1b48 in john_run /home/fd/git/JtR/src/john.c:1358
    #10 0x6d3004 in main /home/fd/git/JtR/src/john.c:1741
    #11 0x7fe0e787e78f in __libc_start_main (/lib64/libc.so.6+0x2078f)

Direct leak of 4216 byte(s) in 1 object(s) allocated from:
    #0 0x7fe0e9538a0a in malloc (/lib64/libasan.so.2+0x98a0a)
    #1 0x6ed586 in mem_alloc_func /home/fd/git/JtR/src/memory.c:89
    #2 0x6ed667 in mem_calloc_func /home/fd/git/JtR/src/memory.c:110
    #3 0x66b0f0 in get_salt /home/fd/git/JtR/src/ssh_fmt_plug.c:239
    #4 0x66ba2c in valid /home/fd/git/JtR/src/ssh_fmt_plug.c:365
    #5 0x6c1d7b in fmt_self_test_body /home/fd/git/JtR/src/formats.c:248
    #6 0x6c4e3f in fmt_self_test /home/fd/git/JtR/src/formats.c:719
    #7 0x6ac0c0 in benchmark_format /home/fd/git/JtR/src/bench.c:243
    #8 0x6adab1 in benchmark_all /home/fd/git/JtR/src/bench.c:661
    #9 0x6d1b48 in john_run /home/fd/git/JtR/src/john.c:1358
    #10 0x6d3004 in main /home/fd/git/JtR/src/john.c:1741
    #11 0x7fe0e787e78f in __libc_start_main (/lib64/libc.so.6+0x2078f)

SUMMARY: AddressSanitizer: 75888 byte(s) leaked in 18 allocation(s).
```
In both cases, the leaks result from the get_salt() calls in valid().

**Comment by frank-dittrich** [comment]
Apparently, commit https://github.com/magnumripper/JohnTheRipper/commit/a3be7a0415fad1b229cc7487a5fecd12e7cb2a38 is not the right fix, or it just exposes another bug.

With ASan, I get a segfault in dyna_salt_remove:
```
$ ./john --nolog --format=SSH hashes.SSH --wordlist=pw.SSH
ASAN:SIGSEGV
=================================================================
==15537==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000045 (pc 0x0000006a874c bp 0x7ffcfaaafc40 sp 0x7ffcfaaafc40 T0)
    #0 0x6a874b in dyna_salt_remove_fp /home/fd/git/JtR/src/dyna_salt.c:50
    #1 0x66eb78 in valid /home/fd/git/JtR/src/ssh_fmt_plug.c:370
    #2 0x6d9e82 in ldr_split_line /home/fd/git/JtR/src/loader.c:698
    #3 0x6dab65 in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:802
    #4 0x6dc339 in read_file /home/fd/git/JtR/src/loader.c:135
    #5 0x6dea67 in ldr_load_pw_file /home/fd/git/JtR/src/loader.c:1000
    #6 0x6d2e2f in john_load /home/fd/git/JtR/src/john.c:1006
    #7 0x6d4502 in john_init /home/fd/git/JtR/src/john.c:1290
    #8 0x6d603d in main /home/fd/git/JtR/src/john.c:1728
    #9 0x7f5aa39f278f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #10 0x406d78 in _start (/home/fd/git/JtR/run/john+0x406d78)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fd/git/JtR/src/dyna_salt.c:50 dyna_salt_remove_fp
==15537==ABORTING
```
hashes.SSH and pw.SSH have been generated from the SSH format self tests.

The self test passes:
```
 $ ./john --test --format=SSH
Will run 8 OpenMP threads
NOTE: This is an ASan debug build, speed will be lower than normal
Benchmarking: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA 32/64]... (8xOMP) DONE
Raw:	104448 c/s real, 14752 c/s virtual
```

```
$ ./john --list=build-info 
Version: 1.8.0.6-jumbo-1-bleeding_omp_asan
Build: linux-gnu 64-bit AVX-autoconf
Time stamp: Thu Jun 18 19:51:34 2015
Arch: 64-bit LE
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 5.1.1 20150612 (Red Hat 5.1.1-3)
gcc version: 5.1.1
GNU libc version: 2.21 (loaded: 2.21)
Crypto library: OpenSSL
OpenSSL library version: 0100010bf
OpenSSL 1.0.1k-fips 8 Jan 2015
GMP library version: 6.0.0
Regex library version: 1.2	(loaded: 1.2.5)
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
Built with these debugging options
	ASan (Address Sanitizer debugging)

```

**Comment by frank-dittrich** [comment]
Commit  95bb9ac reverted commit a3be7a0415fad1b229cc7487a5fecd12e7cb2a38, because a segfault (with or without ASan) is certainly worse than the memleak in valid().

**Comment by frank-dittrich** [comment]
dyna_salt_remove_fp() segfaulted when format was NULL, i.e., when called from within valid().
I fixed that in commit c1c1ce811c9544e528c358fa40f7ef71635e17de and re-applied the fix for the memory leak.

**Comment by frank-dittrich** [comment]
There's still a memory leak in ssh_fmt_plug.c.
But for some reason it only gets reported when not just testing a single format:

```
 (bleeding-jumbo)run $ ../run/john --test --format=ssh* --verbosity=3
NOTE: This is a debug build, speed will be lower than normal
Benchmarking: SSHA512, LDAP [SHA512 256/256 AVX2 4x]... DONE
Many salts:	762500 c/s real, 762500 c/s virtual
Only one salt:	742044 c/s real, 742044 c/s virtual

Benchmarking: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA/PEM 32/64]... DONE
Raw:	46300 c/s real, 46300 c/s virtual

Benchmarking: SSH-ng [RSA/DSA/EC/OPENSSH (SSH private keys) 32/64]... DONE
Raw:	662193 c/s real, 662193 c/s virtual

All 3 formats passed self-tests!

=================================================================
==9881==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4216 byte(s) in 1 object(s) allocated from:
    #0 0x7ff5e0eaab09 in __interceptor_calloc (/lib64/libasan.so.2+0x98b09)
    #1 0x8bf310 in mem_calloc_func /home/fd/git/JtR/src/memory.c:115
    #2 0x839783 in get_salt /home/fd/git/JtR/src/ssh_fmt_plug.c:248
    #3 0x83a0e4 in valid /home/fd/git/JtR/src/ssh_fmt_plug.c:377
    #4 0x8a5385 in ldr_split_line /home/fd/git/JtR/src/loader.c:631
    #5 0x8a658d in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:830
    #6 0x8ab258 in ldr_init_test_db /home/fd/git/JtR/src/loader.c:1099
    #7 0x87731b in benchmark_all /home/fd/git/JtR/src/bench.c:684
    #8 0x8a01e2 in john_run /home/fd/git/JtR/src/john.c:1587
    #9 0x8a19a6 in main /home/fd/git/JtR/src/john.c:1973
    #10 0x7ff5df1f36ff in __libc_start_main (/lib64/libc.so.6+0x206ff)

SUMMARY: AddressSanitizer: 4216 byte(s) leaked in 1 allocation(s).
```

**Comment by jfoug** [comment]
4094eff

**Comment by jfoug** [comment]
nope, no idea.

**Comment by frank-dittrich** [comment]
Tried to dif into it.

First, I checked out commit 1ee9da0, then I modified memdbg.c.

```
((HEAD detached at 1ee9da0))run $ git diff
diff --git a/src/memdbg.c b/src/memdbg.c
index 9ea542d..ad907e3 100644
--- a/src/memdbg.c
+++ b/src/memdbg.c
@@ -1021,6 +1021,7 @@ void MEMDBG_checkSnapshot_possible_exit_on_error(MEMDBG_HANDLE h, int exit_on_an
 
        /* first step, walk allocation list, looking for leaks */
        while (p) {
+               fprintf(stdout, "Mem     : "LLu" bytes, alloc_num %d, file %s, line %d p->mdbg_cnt %d h.alloc_cnt %d memcmp %d\n", (unsigned long long)p->mdbg_size, p->mdbg_cnt, p->mdbg_file, p->mdbg_line, p->mdbg_cnt, h.alloc_cnt, memcmp(p->mdbg_hdr1->mdbg_fpst, cpMEMFPOST, 4));
                if (p->mdbg_cnt > h.alloc_cnt && !memcmp(p->mdbg_hdr1->mdbg_fpst, cpMEMFPOST, 4)) {
                        leak = 1;
                        fprintf(stderr, "Mem leak: "LLu" bytes, alloc_num %d, file %s, line %d\n", (unsigned long long)p->mdbg_size, p->mdbg_cnt, p->mdbg_file, p->mdbg_line);
```

```
((HEAD detached at 1ee9da0))src $ ../run/john --test=0 --format=cpu-dynamic | LC_ALL=C grep -i -C 1 ssh
Will run 8 OpenMP threads
Mem     : 4096 bytes, alloc_num 1, file path.c, line 101 p->mdbg_cnt 1 h.alloc_cnt 437 memcmp 0
Testing: aix-ssha1, AIX LPA {ssha1} [PBKDF2-SHA1 128/128 AVX 4x]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 250, file memory.c, line 54 p->mdbg_cnt 250 h.alloc_cnt 450 memcmp -20480
--
Mem     : 4096 bytes, alloc_num 1, file path.c, line 101 p->mdbg_cnt 1 h.alloc_cnt 450 memcmp 0
Testing: aix-ssha256, AIX LPA {ssha256} [PBKDF2-SHA256 128/128 AVX 4x]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 250, file memory.c, line 54 p->mdbg_cnt 250 h.alloc_cnt 543 memcmp -20480
--
Mem     : 4096 bytes, alloc_num 1, file path.c, line 101 p->mdbg_cnt 1 h.alloc_cnt 543 memcmp 0
Testing: aix-ssha512, AIX LPA {ssha512} [PBKDF2-SHA512 128/128 AVX 2x]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 250, file memory.c, line 54 p->mdbg_cnt 250 h.alloc_cnt 636 memcmp -20480
--
Mem     : 4096 bytes, alloc_num 1, file path.c, line 101 p->mdbg_cnt 1 h.alloc_cnt 31484 memcmp 0
Testing: SSHA512, LDAP [SHA512 128/128 AVX 2x]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 31583, file memory.c, line 54 p->mdbg_cnt 31583 h.alloc_cnt 31574 memcmp -20480
--
Mem     : 4096 bytes, alloc_num 1, file path.c, line 101 p->mdbg_cnt 1 h.alloc_cnt 32290 memcmp 0
Testing: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA/PEM 32/64]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 32483, file memory.c, line 54 p->mdbg_cnt 32483 h.alloc_cnt 32444 memcmp -20480
--
Mem     : 3498 bytes, alloc_num 32457, file loader.c, line 985 p->mdbg_cnt 32457 h.alloc_cnt 32444 memcmp -20480
Mem     : 4216 bytes, alloc_num 32452, file ssh_fmt_plug.c, line 248 p->mdbg_cnt 32452 h.alloc_cnt 32444 memcmp 0
Mem leak: 4216 bytes, alloc_num 32452, file ssh_fmt_plug.c, line 248
Mem     : 16 bytes, alloc_num 31891, file memory.c, line 54 p->mdbg_cnt 31891 h.alloc_cnt 32444 memcmp -20480
```

But when I test just ssh, I get:

```
((HEAD detached at 1ee9da0))src $ ../run/john --test=0 --format=ssh | LC_ALL=C grep -i -C 1 ssh
Will run 8 OpenMP threads
Testing: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA/PEM 32/64]... (8xOMP) PASS
Mem     : 16 bytes, alloc_num 135, file memory.c, line 54 p->mdbg_cnt 135 h.alloc_cnt 136 memcmp -20480
At Program Exit
MemDbg_Validate level 0 checking Passed
```

Which means, memdbg hasn't any idea that there was memory allocated in ssh_fmt_plug.c at all!

(May be I should have opened a new issue for memdbg.)

**Comment by jfoug** [comment]
This 'could' be a bug in memdbg, or in how some pointers are handled in dyna salts.  One the one that shows the leak, look at the alloc_num (i.e. that is a sequence kept of memory allocations within memdbg).  The alloc_num is the same for the one it says is free, and the one it says is the leak!

I made your change, and with the run of -form=ss*  (gets 2 formats), I show the leak, and yes it is like what is shown in your output:

```
Testing: SSH (one 2048-bit RSA and one 1024-bit DSA key) [RSA/DSA/PEM 32/64]... (2xOMP) PASS
Mem     : 16 bytes, alloc_num 246, file memory.c, line 54
Mem     : 4268 bytes, alloc_num 245, file loader.c, line 985
Mem     : 16 bytes, alloc_num 230, file memory.c, line 54
Mem     : 3682 bytes, alloc_num 229, file loader.c, line 985
Mem     : 16 bytes, alloc_num 221, file memory.c, line 54
Mem     : 3544 bytes, alloc_num 220, file loader.c, line 985
Mem     : 16 bytes, alloc_num 212, file memory.c, line 54
Mem     : 3544 bytes, alloc_num 211, file loader.c, line 985
Mem     : 4216 bytes, alloc_num 185, file ssh_fmt_plug.c, line 248
Mem leak: 4216 bytes, alloc_num 185, file ssh_fmt_plug.c, line 248
Mem     : 16 bytes, alloc_num 139, file memory.c, line 54
Mem     : 65536 bytes, alloc_num 138, file dynamic_fmt.c, line 7678
Mem     : 16 bytes, alloc_num 137, file memory.c, line 54
Mem     : 65536 bytes, alloc_num 136, file dynamic_fmt.c, line 7782
Mem     : 16 bytes, alloc_num 135, file memory.c, line 54
Mem     : 65536 bytes, alloc_num 134, file dynamic_fmt.c, line 7678
Mem     : 16 bytes, alloc_num 133, file memory.c, line 54
Mem     : 2407 bytes, alloc_num 132, file dynamic_fmt.c, line 7659
Mem     : 16 bytes, alloc_num 131, file memory.c, line 54
Mem     : 431 bytes, alloc_num 130, file dynamic_fmt.c, line 7493
Mem     : 16 bytes, alloc_num 129, file memory.c, line 54
```
Same alloc num.   So this gives something to go off of.  It appears that only 1 thing was alloc'd, but somehow, there are 2 pointers within memdbg.

**Comment by jfoug** [comment]
No, that double print is just how the code you created is working. there was no else so both printf's were done.

Found the bug.  It is in ssh valid.  This code:

```diff
	if (!(dummy_salt = (get_salt(ciphertext))))
		goto err;
+	prior = dyna_salt_init(self);
	dyna_salt_remove(dummy_salt);
+	if (prior != self)
+		dyna_salt_init(prior);

	MEM_FREE(keeptr);
	return 1;
err:
	MEM_FREE(keeptr);
	return 0;
}
```

I had to change dyna_salt_init() to return whatever was previously initialized. When jtr was run using -form=ssh the dyna salt would be properly initialized to the format prior to the call to valid. If -form=ssh was NOT used, then the dyna salt would be initialized to the LAST hash, for the very first call to valid().  I may look deeper at that, and see if we should be linking the dyna salt prior to that valid call.   But this now does have a cause to look at.

**Comment by jfoug** [comment]
Made a change in loader.c so that the dyna_salt gets initialized at a sooner point. I am running tests now, but I think this bug has been found.

**Comment by jfoug** [comment]
ssh salt is now back to a allocated value that dyna_salt deletes when told to.  The fix to loader.c was the proper fix for this bug.
