### ISSUE TITLE
AddressSanitizer: SEGV for scrypt format (in base64_convert.c:1101)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1259]
64bit Linux, avx2 autoconf build:
```
$ make -s distclean; ./configure --enable-memdbg --enable-asan --disable-openmp && make -s clean && make -s -j 8 && cd ../run
```

```
$ ./john fail_scrypt.pw --format=scrypt
ASAN:SIGSEGV
=================================================================
==12145==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000462499 bp 0x7ffca9b7a540 sp 0x7ffca9b7a520 T0)
    #0 0x462498 in base64_valid_length /home/fd/git/JtR/src/base64_convert.c:1101
    #1 0x448716 in prepare /home/fd/git/JtR/src/scrypt_fmt.c:163
    #2 0x6eaf92 in ldr_split_line /home/fd/git/JtR/src/loader.c:547
    #3 0x6ebbab in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:654
    #4 0x6ed3e2 in read_file /home/fd/git/JtR/src/loader.c:135
    #5 0x6efbdc in ldr_load_pw_file /home/fd/git/JtR/src/loader.c:852
    #6 0x6e47da in john_load /home/fd/git/JtR/src/john.c:981
    #7 0x6e5de2 in john_init /home/fd/git/JtR/src/john.c:1253
    #8 0x6e7a31 in main /home/fd/git/JtR/src/john.c:1686
    #9 0x7fc53e7ca78f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #10 0x406478 in _start (/home/fd/git/JtR/run/john+0x406478)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fd/git/JtR/src/base64_convert.c:1101 base64_valid_length
==12145==ABORTING
```

This is the contents of fail_scrypt.pw:
```
$ScryptKDF.pm$16384*8*1
```

**Comment by frank-dittrich** [comment]
I was worried about travic build failure (clang build), but that was unrelated:
```
The command "sudo apt-get update -qq" failed and exited with 100 during .
```
