### ISSUE TITLE
linux-gnu i686 AVX2, 32-bit build with memdbg: various segfaults

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1270]
This is after reverting commit https://github.com/magnumripper/JohnTheRipper/commit/f86167a4b4945ddf880794d27061ce01cf39d86b, see https://github.com/magnumripper/JohnTheRipper/issues/1268.

I guess memdbg is broken for this build, because so far builds with and without ASan, but builds without memdbg don't show problems.

```
$ ./john --list=build-info
Version: 1.8.0.4-jumbo-1-bleeding_omp_memdbg
Build: linux-gnu 32-bit AVX2-autoconf
Time stamp: Wed May  6 00:07:20 2015
Arch: 32-bit LE
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
Max. Markov mode level: 400
Max. Markov mode password length: 30
File locking: fcntl()
Compiler version: 4.8.3 20140911 (Red Hat 4.8.3-7)
gcc version: 4.8.3
GNU libc version: 2.18 (loaded: 2.18)
OpenSSL library version: 01000105f
OpenSSL 1.0.1e-fips 11 Feb 2013
GMP library version: 5.1.2
fseek(): fseeko64
ftell(): ftello64
fopen(): fopen64
memmem(): System's

Built with these debugging options
	memdbg=on

$ gdb ./john
GNU gdb (GDB) Fedora 7.7.1-21.fc20
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./john...done.
```

```
(gdb) run --test=0 --format=dynamic
Starting program: /home/fd/git/JtR/run/john --test=0 --format=dynamic
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: dynamic_0 [md5($p) (raw-md5) 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb7bb5b40 (LWP 5469)]
[New Thread 0xb73b4b40 (LWP 5470)]
[New Thread 0xb6bb3b40 (LWP 5471)]

Program received signal SIGSEGV, Segmentation fault.
SSEmd5body (_data=0xb7f19050, out=0x8d5d270, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
Missing separate debuginfos, use: debuginfo-install glibc-2.18-19.fc20.i686 gmp-5.1.2-2.fc20.i686 keyutils-libs-1.5.9-1.fc20.i686 krb5-libs-1.11.5-19.fc20.i686 libcom_err-1.42.12-3.fc20.i686 libgomp-4.8.3-7.fc20.i686 libselinux-2.2.1-6.fc20.i686 nss-softokn-freebl-3.18.0-1.fc20.i686 openssl-libs-1.0.1e-42.fc20.i686 pcre-8.33-8.fc20.i686 xz-libs-5.1.2-12alpha.fc20.i686 zlib-1.2.8-3.fc20.i686
(gdb) bt
#0  SSEmd5body (_data=0xb7f19050, out=0x8d5d270, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x08097fc2 in DynamicFunc__crypt_md5 (first=0, last=24, tid=0) at dynamic_fmt.c:4339
#2  0x0809640d in crypt_all._omp_fn.0 () at dynamic_fmt.c:1623
#3  0x0809679d in crypt_all (pcount=0xbfffde0c, salt=0x0) at dynamic_fmt.c:1608
#4  0x08226405 in fmt_self_test_body (salt_copy=0x8dc951c, binary_copy=0x8dc94cc, format=<optimized out>) at formats.c:560
#5  fmt_self_test (format=format@entry=0x8c813f8) at formats.c:710
#6  0x0821b440 in benchmark_format (format=format@entry=0x8c813f8, salts=1, results=results@entry=0xbfffefb0) at bench.c:248
#7  0x0821c393 in benchmark_all () at bench.c:660
#8  0x0822e183 in john_run () at john.c:1337
#9  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=dynamic_0
Starting program: /home/fd/git/JtR/run/john --test=0 --format=dynamic_0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: dynamic_0 [md5($p) (raw-md5) 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb7bb5b40 (LWP 5478)]
[New Thread 0xb73b4b40 (LWP 5479)]
[New Thread 0xb6bb3b40 (LWP 5480)]

Program received signal SIGSEGV, Segmentation fault.
SSEmd5body (_data=0xb7f19050, out=0x8c9b9f0, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
Missing separate debuginfos, use: debuginfo-install glibc-2.18-19.fc20.i686 gmp-5.1.2-2.fc20.i686 keyutils-libs-1.5.9-1.fc20.i686 krb5-libs-1.11.5-19.fc20.i686 libcom_err-1.42.12-3.fc20.i686 libgomp-4.8.3-7.fc20.i686 libselinux-2.2.1-6.fc20.i686 nss-softokn-freebl-3.18.0-1.fc20.i686 openssl-libs-1.0.1e-42.fc20.i686 pcre-8.33-8.fc20.i686 xz-libs-5.1.2-12alpha.fc20.i686 zlib-1.2.8-3.fc20.i686
(gdb) bt
#0  SSEmd5body (_data=0xb7f19050, out=0x8c9b9f0, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x08097fc2 in DynamicFunc__crypt_md5 (first=0, last=24, tid=0) at dynamic_fmt.c:4339
#2  0x0809640d in crypt_all._omp_fn.0 () at dynamic_fmt.c:1623
#3  0x0809679d in crypt_all (pcount=0xbfffde0c, salt=0x0) at dynamic_fmt.c:1608
#4  0x08226405 in fmt_self_test_body (salt_copy=0x8c0f5ac, binary_copy=0x8c0f55c, format=<optimized out>) at formats.c:560
#5  fmt_self_test (format=format@entry=0x8c813f8) at formats.c:710
#6  0x0821b440 in benchmark_format (format=format@entry=0x8c813f8, salts=1, results=results@entry=0xbfffefb0) at bench.c:248
#7  0x0821c393 in benchmark_all () at bench.c:660
#8  0x0822e183 in john_run () at john.c:1337
#9  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=Citrix_NS10
Starting program: /home/fd/git/JtR/run/john --test=0 --format=Citrix_NS10
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: Citrix_NS10, Netscaler 10 [SHA1 256/256 AVX2 8x2]... (4xOMP) [New Thread 0xb74f7b40 (LWP 5520)]
[New Thread 0xb6cf6b40 (LWP 5521)]
[New Thread 0xb64f5b40 (LWP 5522)]

Program received signal SIGSEGV, Segmentation fault.
SSESHA1body (_data=0xb7779050, out=0xb74f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
1086		SHA1_ROUND2a( a, b, c, d, e, SHA1_F,  0 );
Missing separate debuginfos, use: debuginfo-install glibc-2.18-19.fc20.i686 gmp-5.1.2-2.fc20.i686 keyutils-libs-1.5.9-1.fc20.i686 krb5-libs-1.11.5-19.fc20.i686 libcom_err-1.42.12-3.fc20.i686 libgomp-4.8.3-7.fc20.i686 libselinux-2.2.1-6.fc20.i686 nss-softokn-freebl-3.18.0-1.fc20.i686 openssl-libs-1.0.1e-42.fc20.i686 pcre-8.33-8.fc20.i686 xz-libs-5.1.2-12alpha.fc20.i686 zlib-1.2.8-3.fc20.i686
(gdb) bt
#0  SSESHA1body (_data=0xb7779050, out=0xb74f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
#1  0x081255f8 in crypt_all._omp_fn.0 () at citrix_ns_fmt_plug.c:339
#2  0x08125831 in crypt_all (pcount=0xbfffde0c, salt=0x0) at citrix_ns_fmt_plug.c:334
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d5116c, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x8398bc0 <fmt_ctrxns>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x8398bc0 <fmt_ctrxns>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=dynamic_1018
Starting program: /home/fd/git/JtR/run/john --test=0 --format=dynamic_1018
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Testing: dynamic_1018 [md5(sha1(sha1($pass))) 256/256 AVX2 8x2]... 
Program received signal SIGSEGV, Segmentation fault.
SSEmd5body (_data=0xb7eb8050, out=0x8c9b9f0, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
Missing separate debuginfos, use: debuginfo-install glibc-2.18-19.fc20.i686 gmp-5.1.2-2.fc20.i686 keyutils-libs-1.5.9-1.fc20.i686 krb5-libs-1.11.5-19.fc20.i686 libcom_err-1.42.12-3.fc20.i686 libgomp-4.8.3-7.fc20.i686 libselinux-2.2.1-6.fc20.i686 nss-softokn-freebl-3.18.0-1.fc20.i686 openssl-libs-1.0.1e-42.fc20.i686 pcre-8.33-8.fc20.i686 xz-libs-5.1.2-12alpha.fc20.i686 zlib-1.2.8-3.fc20.i686
(gdb) bt
#0  SSEmd5body (_data=0xb7eb8050, out=0x8c9b9f0, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x08091436 in DynamicFunc__crypt_md5_in2_to_out1 (first=0, last=1, tid=0) at dynamic_fmt.c:4743
#2  0x080966f3 in crypt_all (pcount=0xbfffde0c, salt=0x0) at dynamic_fmt.c:1629
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8c0f5ac, binary_copy=0x8c0f55c, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x8c813f8) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x8c813f8, salts=1, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=Citrix_NS10
Starting program: /home/fd/git/JtR/run/john --test=0 --format=Citrix_NS10
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: Citrix_NS10, Netscaler 10 [SHA1 256/256 AVX2 8x2]... (4xOMP) [New Thread 0xb74f7b40 (LWP 7361)]
[New Thread 0xb6cf6b40 (LWP 7362)]
[New Thread 0xb64f5b40 (LWP 7363)]

Program received signal SIGSEGV, Segmentation fault.
SSESHA1body (_data=0xb7779050, out=0xb74f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
1086		SHA1_ROUND2a( a, b, c, d, e, SHA1_F,  0 );
(gdb) bt
#0  SSESHA1body (_data=0xb7779050, out=0xb74f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
#1  0x081255f8 in crypt_all._omp_fn.0 () at citrix_ns_fmt_plug.c:339
#2  0x08125831 in crypt_all (pcount=0xbfffde0c, salt=0x0) at citrix_ns_fmt_plug.c:334
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d5116c, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x8398bc0 <fmt_ctrxns>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x8398bc0 <fmt_ctrxns>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=hdaa
Starting program: /home/fd/git/JtR/run/john --test=0 --format=hdaa
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: hdaa, HTTP Digest access authentication [MD5 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb7067b40 (LWP 7370)]
[New Thread 0xb6866b40 (LWP 7371)]
[New Thread 0xb6065b40 (LWP 7372)]

Program received signal SIGSEGV, Segmentation fault.
SSEmd5body (_data=0xb7df9050, out=out@entry=0xb712f050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
(gdb) bt
#0  SSEmd5body (_data=0xb7df9050, out=out@entry=0xb712f050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x080f6d62 in crypt_all._omp_fn.0 () at HDAA_fmt_plug.c:467
#2  0x080f77c3 in crypt_all (pcount=0xbfffde0c, salt=0x0) at HDAA_fmt_plug.c:430
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d51164, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x83949a0 <fmt_HDAA>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x83949a0 <fmt_HDAA>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test --format=HMAC-MD5
Starting program: /home/fd/git/JtR/run/john --test --format=HMAC-MD5
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Benchmarking: HMAC-MD5 [password is key, MD5 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb6f0bb40 (LWP 7380)]
[New Thread 0xb670ab40 (LWP 7381)]
[New Thread 0xb5f09b40 (LWP 7382)]

Program received signal SIGSEGV, Segmentation fault.
SSEmd5body (_data=0xb7978050, out=0xb75b6050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
(gdb) bt
#0  SSEmd5body (_data=0xb7978050, out=0xb75b6050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x0816d92b in crypt_all._omp_fn.0 () at hmacMD5_fmt_plug.c:389
#2  0x0816d9a3 in crypt_all (pcount=0xbfffde0c, salt=0x0) at hmacMD5_fmt_plug.c:383
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d51161, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x839e5a0 <fmt_hmacMD5>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x839e5a0 <fmt_hmacMD5>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=HMAC-SHA1
Starting program: /home/fd/git/JtR/run/john --test=0 --format=HMAC-SHA1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: HMAC-SHA1 [password is key, SHA1 256/256 AVX2 8x2]... (4xOMP) [New Thread 0xb7443b40 (LWP 7390)]
[New Thread 0xb6c42b40 (LWP 7391)]
[New Thread 0xb6441b40 (LWP 7392)]

Program received signal SIGSEGV, Segmentation fault.
SSESHA1body (_data=0xb7b78050, out=0xb78d6050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
1086		SHA1_ROUND2a( a, b, c, d, e, SHA1_F,  0 );
(gdb) bt
#0  SSESHA1body (_data=0xb7b78050, out=0xb78d6050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:1086
#1  0x0816ed0f in crypt_all._omp_fn.0 () at hmacSHA1_fmt_plug.c:343
#2  0x0816ed83 in crypt_all (pcount=0xbfffde0c, salt=0x0) at hmacSHA1_fmt_plug.c:337
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d51169, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x839e820 <fmt_hmacSHA1>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x839e820 <fmt_hmacSHA1>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=HMAC-SHA224
Starting program: /home/fd/git/JtR/run/john --test=0 --format=HMAC-SHA224
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: HMAC-SHA224 [password is key, SHA224 256/256 AVX2 8x]... (4xOMP) [New Thread 0xb6793b40 (LWP 7401)]
[New Thread 0xb5f92b40 (LWP 7402)]
[New Thread 0xb5791b40 (LWP 7403)]

Program received signal SIGSEGV, Segmentation fault.
SSESHA256body (data=0xb7778050, out=0xb7176050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=8192) at sse-intrinsics.c:1595
1595				vstore((vtype*)&(out[i*8*VS32+0*VS32]), a);
(gdb) bt
#0  SSESHA256body (data=0xb7778050, out=0xb7176050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=8192) at sse-intrinsics.c:1595
#1  0x0816ff7b in crypt_all._omp_fn.0 () at hmacSHA224_fmt_plug.c:349
#2  0x0816fffb in crypt_all (pcount=0xbfffde0c, salt=0x0) at hmacSHA224_fmt_plug.c:340
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d51171, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x839ea20 <fmt_hmacSHA224>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x839ea20 <fmt_hmacSHA224>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=ipb2
Starting program: /home/fd/git/JtR/run/john --test=0 --format=ipb2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: ipb2, Invision Power Board 2.x [MD5 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb7735b40 (LWP 7412)]
[New Thread 0xb6f34b40 (LWP 7413)]
[New Thread 0xb6733b40 (LWP 7414)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb6733b40 (LWP 7414)]
SSEmd5body (_data=_data@entry=0xb7eb9050, out=out@entry=0xb7c48050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
323				vstore((vtype*)&out[i*4*VS32+0*VS32], a[i]);
(gdb) bt
#0  SSEmd5body (_data=_data@entry=0xb7eb9050, out=out@entry=0xb7c48050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:323
#1  0x080f8855 in crypt_all._omp_fn.0 () at IPB2_fmt_plug.c:368
#2  0x46d84416 in gomp_thread_start (xdata=0xbfffdc10) at ../../../libgomp/team.c:117
#3  0x46ccbd4c in start_thread (arg=0xb6733b40) at pthread_create.c:309
#4  0x46bfb74e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
```

```
(gdb) run --test=0 --format=mscash2
Starting program: /home/fd/git/JtR/run/john --test=0 --format=mscash2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: mscash2, MS Cache Hash 2 (DCC2) [PBKDF2-SHA1 256/256 AVX2 8x2]... (4xOMP) [New Thread 0xb7f79b40 (LWP 7421)]
[New Thread 0xb7778b40 (LWP 7422)]
[New Thread 0xb6f77b40 (LWP 7423)]

Program received signal SIGSEGV, Segmentation fault.
SSESHA1body (_data=_data@entry=0x8d6af70, out=out@entry=0x8d6af70, reload_state=reload_state@entry=0x8d72fd0, SSEi_flags=SSEi_flags@entry=40) at sse-intrinsics.c:1065
1065					a[i] = vload((vtype*)&reload_state[i*16*VS32+0*VS32]);
(gdb) bt
#0  SSESHA1body (_data=_data@entry=0x8d6af70, out=out@entry=0x8d6af70, reload_state=reload_state@entry=0x8d72fd0, SSEi_flags=SSEi_flags@entry=40) at sse-intrinsics.c:1065
#1  0x08193dcc in pbkdf2_sse2 (t=<optimized out>) at mscash2_fmt_plug.c:617
#2  crypt_all._omp_fn.1 () at mscash2_fmt_plug.c:743
#3  0x08193f57 in crypt_all (pcount=0xbfffde0c, salt=0x0) at mscash2_fmt_plug.c:722
#4  0x08226405 in fmt_self_test_body (salt_copy=0x8d51162, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#5  fmt_self_test (format=format@entry=0x83a2260 <fmt_mscash2>) at formats.c:710
#6  0x0821b440 in benchmark_format (format=format@entry=0x83a2260 <fmt_mscash2>, salts=256, results=results@entry=0xbfffefb0) at bench.c:248
#7  0x0821c393 in benchmark_all () at bench.c:660
#8  0x0822e183 in john_run () at john.c:1337
#9  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

```
(gdb) run --test=0 --format=Raw-MD4
Starting program: /home/fd/git/JtR/run/john --test=0 --format=Raw-MD4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Will run 4 OpenMP threads
Testing: Raw-MD4 [MD4 256/256 AVX2 8x3]... (4xOMP) [New Thread 0xb77f7b40 (LWP 7441)]
[New Thread 0xb6ff6b40 (LWP 7442)]
[New Thread 0xb67f5b40 (LWP 7443)]

Program received signal SIGSEGV, Segmentation fault.
SSEmd4body (_data=0xb7979050, out=0xb77f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:764
764		MD4_STEP(MD4_G, b, c, d, a, 15, cst, 13)
(gdb) bt
#0  SSEmd4body (_data=0xb7979050, out=0xb77f8050, reload_state=reload_state@entry=0x0, SSEi_flags=SSEi_flags@entry=0) at sse-intrinsics.c:764
#1  0x081c8b77 in crypt_all._omp_fn.0 () at rawMD4_fmt_plug.c:292
#2  0x081c8d97 in crypt_all (pcount=0xbfffde0c, salt=0x0) at rawMD4_fmt_plug.c:287
#3  0x08226405 in fmt_self_test_body (salt_copy=0x8d51161, binary_copy=0x8d51114, format=<optimized out>) at formats.c:560
#4  fmt_self_test (format=format@entry=0x83aa700 <fmt_rawMD4>) at formats.c:710
#5  0x0821b440 in benchmark_format (format=format@entry=0x83aa700 <fmt_rawMD4>, salts=1, results=results@entry=0xbfffefb0) at bench.c:248
#6  0x0821c393 in benchmark_all () at bench.c:660
#7  0x0822e183 in john_run () at john.c:1337
#8  0x0822f09c in main (argc=3, argv=0xbffff254) at john.c:1709
```

etc.

Any idea what to look for?

**Comment by frank-dittrich** [comment]
Could that be alignment issues?

**Comment by magnumripper** [comment]
It's almost definitely caused by MEM_ALIGN_SIMD alignments not ending up as 32 for AVX2. But I can't see why.

Oh wait, I can see why. My bad. I will need to adjust what I did in 8506e3cc16 depending on sizeof(pointer)!
