### ISSUE TITLE
Keyring format segfaults in 32-bit OSX (real gcc) AVX2 build

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1292]
```
Testing: keyring, GNOME Keyring [SHA256 AES 256/256 AVX2 8x]... (4xOMP) Segmentation fault: 11
```

**Comment by magnumripper** [comment]
This is not seen with a 32-bit AVX build.

**Comment by magnumripper** [comment]
This is not seen when running just one thread. Running two or more threads, it segfaults with lldb pointing out line 311 which is an OpenMP pragma line.

**Comment by frank-dittrich** [comment]
can you build with libtsan (Threadsanitizer) support (-fsanitize=thread) and see if that provides useful info?

**Comment by magnumripper** [comment]
It appears -fsanitize=thread is only supported for 64-bit

**Comment by magnumripper** [comment]
Dropping the pragma, it runs fine (serialized). This rules out many bugs but leaves the possibility it's actually a compiler bug.

**Comment by magnumripper** [comment]
Adding explicit declarations to the pragma did not help nor reveal any problem.

**Comment by magnumripper** [comment]
I tried undefining SIMD_COEF_32, forcing a non-SIMD build of that format. Problem disappeared.

**Comment by magnumripper** [comment]
Using gcc 5.1 did not change anything (and also does not support -santitize=thread)

**Comment by magnumripper** [comment]
```
$ ../run/john -test -form:keyring
Will run 4 OpenMP threads
NOTE: This is an ASan debug build, speed will be lower than normal
Benchmarking: keyring, GNOME Keyring [SHA256 AES 256/256 AVX2 8x]... (4xOMP) ASAN:SIGSEGV
=================================================================
==17402==ERROR: AddressSanitizer: stack-overflow on address 0xaffc0eac (pc 0x001f28c4 bp 0xb0080f28 sp 0xaffc0eb0 T1)
    #0 0x1f28c3 in crypt_all._omp_fn.0 keyring_fmt_plug.c:310
    #1 0x1410066 in gomp_thread_start (in libgomp.1.dylib) + 374

SUMMARY: AddressSanitizer: stack-overflow ??:0 ??
Thread T1 created by T0 here:
    #0 0xec07fd in wrap_pthread_create (in libasan.2.dylib) + 77
    #1 0x14104db in gomp_team_start (in libgomp.1.dylib) + 763
    #2 0x140cec3 in GOMP_parallel (in libgomp.1.dylib) + 51

==17402==ABORTING
```

**Comment by magnumripper** [comment]
OK, here is a fix that works
```
diff --git a/src/keyring_fmt_plug.c b/src/keyring_fmt_plug.c
index 8da2abf..57d9685 100644
--- a/src/keyring_fmt_plug.c
+++ b/src/keyring_fmt_plug.c
@@ -73,7 +73,7 @@ static struct custom_salt {
        unsigned char salt[SALTLEN];
        unsigned int crypto_size;
        unsigned int inlined;
-       unsigned char ct[LINE_BUFFER_SIZE / 2]; /* after hex conversion */
+       unsigned char ct[LINE_BUFFER_SIZE / 4];
 } *cur_salt;
 
 static char (*saved_key)[PLAINTEXT_LENGTH + 1];
```
This is troubling. Apparently the crazy size of Jumbo's LINE_BUFFER_SIZE is too much (it's multiplied with SIMD_COEF_32, in this case 8, and that seems to go past some limit).

0x30000 * 4 == 786432
0x30000 * 8 == 1572864
