### ISSUE TITLE
External mode: Floating point exception

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1362]
# 1. Reproduce

$ ./configure && make -sj8
$ cat test_pw
```
$apr1$a2Jqm...$grFrwEgiQleDr0zR4Jx1b.
```
$ cat local.conf
```
[List.External:Lanman]

void init()
{
	int i;

	i/= 0;
}

void generate()
{
}


void restore()
{
}
```
$ ../john test_pw --format=md5crypt --external=lanman --config=local.conf
```
Floating point exception
```

# 2. GDB debug

$ set args test_pw --format=md5crypt --external=lanman --config=local.conf
$ r
```C
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGFPE, Arithmetic exception.
0x00000000005c1660 in c_execute_fast (addr=<optimized out>) at compiler.c:1137
1137		imm = *(sp - 3)->mem /= imm;
(gdb) bt
#0  0x00000000005c1660 in c_execute_fast (addr=<optimized out>) at compiler.c:1137
#1  0x00000000005c53a2 in ext_init (mode=0x10c712d "lanman", db=<optimized out>) at external.c:190
#2  0x00000000005ccec4 in john_load () at john.c:922
#3  0x00000000005cda86 in john_init (name=0x7fffffffec32 "john", argc=5, argv=0x7fffffffe988) at john.c:1280
#4  0x00000000005ce772 in main (argc=5, argv=0x7fffffffe988) at john.c:1707
```

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2015/05/30/12
