### ISSUE TITLE
NETNTLMv2_fmt: malloc(): memory corruption (fast)

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1393]
This bug is found by afl.

# 1. Reproduce

$  ./configure && make -sj8
$ cat pwfile
```
100000000f1dc96f425971ba590a076fd0f8bccbf25c1ba0c
14623718525fe334bbd9c0704e06ce134ef17b51f6b33558c
15c5c5c5c6ccd884f6383f55a6aeba5f847775e57ab012675
13333333319143136ba9ff9e18d1cb022b63df0926de9509e
144434241d7ce89a7484cd202400639692258dde37efc29c4�100010203e09cefed1847b7a2a5e7a5d2cdc6:e8a56ed0bdd
14dfca1e6c0f5f3d96526c3ce70849992b7fad3e324cf6b0f
1deadcafe7587ea23b25a6ccf3fd53192e36ad3e9a553b20
```
$ ./john pwfile
```C
Warning: invalid UTF-8 seen reading out/crashes/id:000003,sig:06,src:000012,op:havoc,rep:4
*** Error in `../../john': malloc(): memory corruption (fast): 0x0000000002e791a0 ***
Aborted
```

# 2. GDB debug

```C
Program received signal SIGABRT, Aborted.
0x00007ffff6668cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6668cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff666c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff66a5394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff67b3b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff66b00f7 in malloc_printerr (action=<optimized out>, str=0x7ffff67b3ec8 "malloc(): memory corruption (fast)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff66b2e04 in _int_malloc (av=0x7ffff69f0760 <main_arena>, bytes=103) at malloc.c:3359
#5  0x00007ffff66b47b0 in __GI___libc_malloc (bytes=103) at malloc.c:2891
#6  0x00000000005d825e in mem_alloc_func (size=103) at memory.c:89
#7  0x00000000004b1727 in prepare (split_fields=0x0, self=0x74707572726f6320) at NETNTLMv2_fmt_plug.c:240
#8  0x00000000005cd08e in ldr_split_line (login=0x0, ciphertext=0x7b0, ciphertext@entry=0x7ffffffce608, gecos=0x6, gecos@entry=0x7ffffffce610,
    home=0x7ffff6668cc9 <__GI_raise+57>, home@entry=0x7ffffffce618, uid=0x3, source=0x93c700 <fmt_NETNTLMv2> "\344\237d", format=0xfac228 <database+104>,
    db_opts=0xfac228 <database+104>, line=0x0) at loader.c:640
#9  0x00000000005cdb1e in ldr_load_pw_line (db=0xfac1c0 <database>, line=<optimized out>) at loader.c:802
#10 0x00000000005cbba1 in read_file (db=0xfac1c0 <database>, name=0x10ca118 "out/crashes/id:000003,sig:06,src:000012,op:havoc,rep:4", flags=<optimized out>,
    process_line=0x5cdae0 <ldr_load_pw_line>) at loader.c:135
#11 0x00000000005c9f5a in john_load () at john.c:1006
#12 0x00000000005ca7f5 in john_init (name=0x7fffffffec0d "john", argc=2, argv=0x7fffffffe978) at john.c:1290
#13 0x00000000005cb4e6 in main (argc=2, argv=0x7fffffffe978) at john.c:1730
```

**Comment by jfoug** [comment]
Can this issue be checked out after cf9c4c1

**Comment by loverszhaokai** [comment]
@jfoug  Fixed. Thanks.
