### ISSUE TITLE
NETLMv2_fmt: malloc(): memory corruption (fast) [2]

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1398]
This bug is found by afl.

This problem seems like https://github.com/magnumripper/JohnTheRipper/issues/1394, but the **gdb backtrace** is different, so they are maybe different bug.

# 1. Reproduce

$  ./configure && make -sj8
$ cat pwfile
```
$django$*1*pbkdf2_sha256$10000$qPmFbibfAY06$x/geVEkdZSlJMqvIYJ7G6i5l/6KJ0UpvLUw6cbj83VM=
$django$*1*pbkdf2_sha56$10000$BVmp`MBhRSd7$2nTDwPhSsDKOwpKiV04teVtf+a14Rs7na/lIB3KnHkM=
$django$*1*p~kdf2_sha25kdQo9RoatRomupPFP+XEo+Guuirq�mi+R1cFcV0U3M=
$django$*1*pbkd�2_sha256$10000$BVmpZMBhRSd6$Uq33DAHOFHUEm4GB8hOjTLQqvBfxJ2/OJ7YwFf6h+6k=
$django$*1*phkdf2_sha256$10000$34L3roCQ6ZfN$17d37881cb92e6BfBocefFfuGVwE3pXcLEhChc+pU=
$django$*1*pbkdf2_sha256$10000$7qPqyUDw8kZV$pFmVR�lHvayoWEySZWXkHgfmgIm:KLmkmruclpYVAxM=
```
$ ./john pwfile
```C
Warning: invalid UTF-8 seen reading out/crashes/id:000042,sig:06,src:000029,op:havoc,rep:16
*** Error in `../../john': malloc(): memory corruption (fast): 0x0000000002a5e240 ***
Aborted
```

# 2. GDB debug

```C
Program received signal SIGABRT, Aborted.
0x00007ffff6668cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6668cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff666c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff66a5394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff67b3b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff66b00f7 in malloc_printerr (action=<optimized out>, str=0x7ffff67b3ec8 "malloc(): memory corruption (fast)", ptr=<optimized out>) at malloc.c:4996
#4  0x00007ffff66b2e04 in _int_malloc (av=0x7ffff69f0760 <main_arena>, bytes=85) at malloc.c:3359
#5  0x00007ffff66b47b0 in __GI___libc_malloc (bytes=85) at malloc.c:2891
#6  0x00000000005d825e in mem_alloc_func (size=85) at memory.c:89
#7  0x00000000004af127 in prepare (split_fields=0x0, self=0x74707572726f6320) at NETLMv2_fmt_plug.c:231
#8  0x00000000005cd08e in ldr_split_line (login=0x0, ciphertext=0x13f58, ciphertext@entry=0x7ffffffce608, gecos=0x6, gecos@entry=0x7ffffffce610,
    home=0x7ffff6668cc9 <__GI_raise+57>, home@entry=0x7ffffffce618, uid=0x3, source=0x93bac0 <fmt_NETLMv2> "\230\230d", format=0xfac228 <database+104>,
    db_opts=0xfac228 <database+104>, line=0x0) at loader.c:640
#9  0x00000000005cdb1e in ldr_load_pw_line (db=0xfac1c0 <database>, line=<optimized out>) at loader.c:802
#10 0x00000000005cbba1 in read_file (db=0xfac1c0 <database>, name=0x10ca118 "out/crashes/id:000042,sig:06,src:000029,op:havoc,rep:16", flags=<optimized out>,
    process_line=0x5cdae0 <ldr_load_pw_line>) at loader.c:135
#11 0x00000000005c9f5a in john_load () at john.c:1006
#12 0x00000000005ca7f5 in john_init (name=0x7fffffffec0c "john", argc=2, argv=0x7fffffffe978) at john.c:1290
#13 0x00000000005cb4e6 in main (argc=2, argv=0x7fffffffe978) at john.c:1730
```

**Comment by jfoug** [comment]
Can this issue be checked out after cf9c4c1

**Comment by loverszhaokai** [comment]
@jfoug Fixed. Thanks.
