### ISSUE TITLE
loader.c 914: Segmentation fault

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1402]
This bug is found by afl.

# 1. Reproduce

$  ./configure && make -sj8
$ cat pwfile
```
$ssh2$2d2d2d2d2d424547494e201253412050524956415445204b45592d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204445532d454445332d4342432c464446343843343633303936433641360a0a2f4f6548434273304156786472773771564d646e2b68624a524f4f7454446f3376503371436678426c534b54627547676d4d39726b387866756b4f394b706a560a4a513136676a4a35366976375558393345486e466873454264706371395441544e3574733741655973374d73687961346532496f78616c634a377053427362670a5a2f69344f67327954317477586c4f655464716f413354444f68382b5750496d47426133785a412b4e334a4947354e306e526b6757466263354a554a46767a6f0a766c2f3545437466324143455a37744b39325a56556e59464f6c2b6a59525a665a456f664f38725169496f3236594668547a6c694258384b6b566777575756440a344a31797563427576675365583046574b566f6554306f574232353379316e686a386a6150784262663930664b5a666e394945764438482f4a4c4e4c38736a790a53787965557a356d714372695a44786254796d6153697348704b61464d2f63627743625a2f764954384a486a69555657543531715871484e61522f63617764610a647a6b7a6e4d516b57475645377947613476484c56417166764c77362b4e56475950474170614a5668414a5132423235356362526e454e496c356466544437760a717348684b6a78387a2b43453976326270754c516e7179746e6c654638414f2b764d39426e4667306d4e5169585a75584a54305833425152706b4845724a435a0a4f4f736f6e6c6c6a32684f46764b3479504468694c453672394b386a6a44766b58554339375755663742303751536362576871386b64566c43355532493341680a6e50515035354d66452f52535a544837306159562b64647278526f62543768506a44306332394e7666313745314e793437776c696b567072742f352b516c36310a67336e52454c786662664c67517451434673566c4b454f6c32356a57786c6c526759522f794e3165767a4a333673516231574d4747417239386e6a346f7646310a2b34705152616b6d6c58784f535335362b754b58365255434b62534635764b50516e49364b33745871545a36314e487a726254456469554c635a54507a6769730a37564f3064786e317a34437343415a4975634c69645547744d6d6c615953686a547843432f2f5247645a442b46597054666a73592b76473932793436314c536b0a4d4c705034686d436f34705a31644e636c594f716d614b68483553357459496a69617970576d63784f34524f4432707132335337785a71394e467a4948676a660a4e5064322f5671696274516c6a326f6a6335476d32784b73777243356334785759735978376a766c3369706a7168385269516d3478536c43505376304e6765540a6a77374979754b3847785233714a4641506f42516968506c7663692f794b544e6d456d6e2b733850566d70394d70725a6c496952365345502f453044385748760a794862462f6e56534a484b674252584f2f694f6a526e5576416b6f38557254353043687046513746734a384e695255386b586c4f434c59714778594e484a4d700a543042706159506343312b704d5345744675516c513277797a6473784574574a69306c55666335465331516c7a3870646d4659744e4a66794f7252356b502f4e0a4570424833792b795939704279386b62466b71526e6d55564477686768454f33654c6c564e4e566438324e5a7a464a4a32617777776a31794e345a3042617a660a4e455839543146684c496e634c4e7241696e4c4c32474f42737036533379426f5474796c477a5264326b4b484a74686c6261674b73336a3138375571673652350a53376c6b2b3269366c787344574d7a6772312f4e782b77662b3479572b622f506663747a4637716e68695441563473576e63304e5175476732494f74613875760a494d32456c474675684c465335636a49333875644c32384d2f4354376b4c436b5658342b622b5a444551472f5956697a4f6d4f704d5842594f4c6658586751390a534c6f2b323278555548744c4a434e2b66384d7154395a3141677043484270315a6c4b73357831464d7267433771666c4a73667a4d6e5a63534764706538766b0a46743954593756396a6e4132424a5a4f6f46717a6634533059676c477458545358376c6b4566506355475739696d6463777a554772626170334b2b687a6b4c4a0a4e2b4b4f4830772f46537143312f63436857646b7167767131497465773373716d7854477739446e575a35666735726b4f504f5670673d3d0a2d2d2d2d2d454e44205253412050524956415445204b45592d2d2d2d2d0a*1743
$ssh2$2d2d2d2d2d424547494e204453412050524956415445204b45592d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c35413830363832373943304634364539383230373135304133433245433631340a0a2f756954696e4a3452556a6f5a76302b705931694d763163695661724369347a2f62365a694c4161565970794a31685854327463692b593266334c61614578630a6f357772316141464d3437786d526d476f3832492f76434847413952786735776147433970574f475a5675555172447355367463556b434d422b325a344753390a354f44474364444b32674e6574446e62324a764873714154736d3443633633476468695a30734346594c71796d2b576531774359616c78734f3231572b4f676f0a42336f6746464977327232462b714a7a714d37415543794c466869357a476d7536534e6558765534477a784750464a4e47306d414f55497761614e3161446a630a4e326b3462437266796271337a366e436533444273384b3232694e2b3875526e534162434f717a5a5845645971555959354b6b6a326e654354525458494e64670a512b61535359673379355937626f4b6b6a494f727650555748654f796475512b74657273414577376e43564a7a72394e387452673271563450557631434b66700a4f49467742372f39736f6d6a59496a71576f61537a6a784b30633852777a305331706d722b7571726277792b50656f75354d3373656d486c426b4769553237660a776f684b792b4d554e4862734e6a7973535a53456c4e4b734d4950715449567a5a45316d5646412f30754d477164705133627a424f6a58325a6f36656446434f0a6d4a34775961765735774d2b6a6d75564b5056564e7939395a78796570304645644c50354b623263345a6c3053396631342f62366836415069785665377a75760a5662536b4279664a6e797a68494f5942497954374d64773134723441584a56362b5a6f457730397769774d3d0a2d2d2d2d2d454e44204453412050524956415445204b45592d2d2d2d2d0a*771
$ssh2$2d2d2d2d2d424547494e205253412050524956415445204b45592d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c41304238464341423242363535424133443034423230323042383941313432450a0a704e75307853616d76714f757969626d324a384d476576667552564d354d3230752f773049502f4f574e317134516439757064546f4147794b77666b4a4975790a314b50457679793635442b4d4b6656635044624756717079597630765170715066377845504264576837494d654f302b514a6f442b33734b2b694c764c36316a0a3159444f414f4d5a5342635868366947486a545579576251785530706c595866645870326f6e6a436a6f6d626578622b644e4f4b32665969436936373072516e0a6f2f4b554e7636793441436a38624a714f5162726844464b6a34334345613672446c316364327455705a77324d4b6c74355162392f50656d6d527575547044760a4c322b5a31616b73654f336348337658577053385279777937344b31596d47496d6d44377275344c4646784b7034572f2b4c6855754d5966336a38426a6844700a744e35767631716e2f7a445a6861693432683556525a68567a5a59486251336c2f7a476c6b38702f394c72624234686f434d596b7a712b5656576b546a4666390a6b41614866596f585338347a5237636b6b4e555948594f694251446353656757445164575762566f676772436549705171364249696c6d4d625a43434543624a0a7069452f4a357548632b73385732436e506b675a6e74664c706d5756352f495a784e4431346a45686c686e2f76543137306472557261692f6a5a3362315447660a39486b69356f574a526e654e727735725235633974333957334d4e5761527a4d5a537a4e55396e356956794a625a6e5044456d4f576f31784c79364b465a71410a364b506d6934456d55504464734f457742446935465054436a534d735244646f764d7272494549535355654341444e44706339745256755637386c4d6a5a56550a54624d7342546e5134667743694c58732f4c784c7437596e696c514a4f6c6273437457536a42453671576f5254582f547273467a645a3963434238644369384a0a496b4d2f38586b526b4277504435514c487a526446683252374e524662707545574b464f443875764b3355434163454d2f7a79504f484145755a766c466652630a4143414f2f71546a62594e53536e594d4946474e6b4334343168496237796d306565322f524c354d55584d4d4f37794733577138514c5a30634f4572676a584c0a4578653232754e4e6d5353504f6f2b597033324567324441476d526664734f72772f5a71384e4877393775336554437a2b46517742692b78714378612f784e510a76626f456d6f7648764d4d2b5966302b68495335357455656f53457a653356544b457a5249696f6b61654848465938542f324d776454416b4f764a62537a62520a6d36426751684c7279304b30554d5231346a6a43756641684349735771732b32355754752b4768672f51642f6b4e354848384a6d495459474365556d524535310a5672754e626563444a78704c714e3743564442633052592f6b4b4d74695762316d5a4139344f53324c6a714e735664542b776d64466b326231457746385750390a6c75397a4f4378336b685449374a4e4a6a7939666f7870307257724445326f337876624365783358755477654b533875384e56705742394679776448376c6f760a79365634484e795775624c7765397576662f54675179687a427945532f5264354c4a46556735504e574b667269784a76462b345166355a77566e774b747561350a6f706c77564e6c6f2f724b6652352b34743469424f4a636146434b4c7252685532594250472b70334155742f4452413352454634316d3074735a746d4450586f0a52796179397a426d4b6833354f727855726c4964505261522b302b6b6977682b725a33387a30356a5a396d6958306967476161762b2b79457767726e735177710a46707a364236545362464131774330376651466f472f5672395769724833514d6875357651376930514f366838524f6169667062786c4d5752436146626a70650a4976396637515736656756506255594a3678517538524f69547757354b366373514d326233676e59456c31474c394d4c7178584c52784d506f776377736d774e0a4f5a30557563744337466266416b7535753830597130306e6e4d2b437373482b36503236336f7656426e6b616239555453624a4d3344627354596a6d33554f6f0a57354b6e46466951676e48536d476766564b7057636d4c386343594d7756312f56566d72312b667554537838636e7631413278476d326b4f7a7061556743514d0a2d2d2d2d2d454e44205253412050524956415445204b45592d2d2d2d2d0a*1766
$ssh2$2d2d2d2d2d424547494e205253412050524956415445204b45592d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c39323546413041324546373238334132463639433643453639313231443433430a0a424a68414b46483951464555714743682f63646764537649742f524d64374c76616d314737547a75534e6c6a767a533542524a4d474949377870675a752b77700a37657630357065762f2b77734e6565626d542f7969354c514e5664597563547141507366533953484d67575751386f68524c6e4458656330324e73355548624c0a6641526f39732b3675785a474e462b516576677238566d484d39657170556c7356655a69423131723230664c6c4246672f52454756774d4430416d39794a2b6a0a374d4238684d5035456a696c48626a73774a2b4f613277546c6335586c77792f4b6a37784e4233637441547057444c7755316f77735842495655737a5156416d0a4763534768647448426f5663356971477335552f45686e553275454351795a6441535a50706b43414268694b5147672b586553564c4c5a35624e4a5a50704e6c0a426c39522f7947794f347641645552534a676b726d4945556c693756394c6c784b4d7870374b656a305261644c594f6d4d71584d55536b464a3779456a4833540a31325655736f75797671426962302f53667a7557454f676e3643456359496564642b6f566b39674a4347474c56516751534c7772727661456a45454463726d6d0a6b316a2b7556776a3130663447316c586647416456544e3766484e39643731304b6846576761643477396a6c4536504d306c7a344d364d7363373845523245780a7372744a6a3679556c6c6c7859335a7258305a724a48696c5a484e734a467a776f4c394c4d37345436794e6732737634567a73304c7a4e74413045696c6c544e0a46415a307359343177452b5265705a6f4d47744d6b7968594a623349535577676e52417945756f64367365446e624b4b7a375550713858437451567a4d2b79380a746f5774373136574b6c4a7141763145394170612b634a39516847764570725565312b3848562b6641655774484650334b4f7257616b584c6a6d7163456a65750a73434e30496c3779746a7644366d7372477259546235416a6274586558346a473764364f703132347a35727467444254647a4866342b36465772554238434e610a36775849737550305a6f796771794d4d79485a495937382b70787538346e59315671464d3346344a7350714f6e4f61556a54643743482f6754527061347370680a4e5155554e327a305278476672513668574c46726872365051335176755a4e4e5042364d78475358775a485263447146344c697841724a316c556357683858520a4d316f696b43465031473256614e537968467549385262567772506a646d4177767250584556662f44452b723054716863336c647462694e425a37486d2f554d0a49764d526c4247304a35306366413649703741667048355356546b54734d37754a7955412f742b6968494f6f536347477a6a477945306c46334b71457754392b0a5230315a734b44313932696f37457a566a49535a73376f2b47494436643254716e6b4a4c4b65583236704e6e4738347068656f4e55652f4364303843504758700a6d2b50625638536f506a77765766376d4c3244366a483632622f687738467a2f312b6f67685343675a412f6f6232475a524c4f4a7a2b6156566e3638676f4b550a42796336786e4577303743636a2f46797033714f3957735971735a64566766766e32376e6b6344735732524876595237585770554552517145516341316273450a516b45523366376963546e72725a4d6470673368364c2f4966797454754849454e6450627331684558384e4a4f7470434753654464423979745a4e4e616a6d650a487146696b66725a3834354a386a3436317a41395452355764376d6f47762b4e2f4b6572737a5256354f65466970336d5675516a6e434b734c704731574c7a430a577a567235594e49662f776b525a687a2f723072374b3567566c524e5676356e413049306345696f71386f426e53494465552f595a533078695a384a545765710a4d4530655948526737373377577a74416665565079654d3947486e2b5633435241327433354434344c78724c76424c4c4f38672f4a615235456d56304867474c0a5343572b734b61514862476535596f384e3433302f2b744d6e65392b63776f495647302f6159396370506d4d676436796d4363707135555766737168316a494c0a4574535054654c386d4a473434526649696d39622f77527248716a4b744c4376696b694e2b6d4e547a4b6f784a656c5a4d69765172555a69725258502b34627a0a2d2d2d2d2d454e44205253412050524956415445204b45592d2d2d2d2d0a*1766
$ssh2$2d2d2d2d2d424547494e205253412050524956415445204b45592d2d2d2d2d0a50726f632d547970653a20342c454e435259505445440a44454b2d496e666f3a204145532d3132382d4342432c41424638364346373834394242433543363631413639463146374234433837410a0a5355484c486a305a2f58467a35376c2f723253453241502b5a7a6469676b486e3645693030433732504a47706d72715544424668562f6c7566493652565133310a486667444a4b566a416b5375672f7a415177544b6e33704e6c69484b74467074555472384272493254434971655164796e6a5669396e62376c4e656a7a374a560a48654a326270316e7744582b7a6552562f5851615a3149644433466e5058773253734d5568514d557378746f6d526d46524d44797133694f76554e63307047750a6a424a5861446633684b7438324b6d384a4c366a676a41304655337873396d326f47515447703634477a2f536d50456f52597a383546417756674c67682b715a0a562b4b524635517535364c396970674e70567732543367663772472f4e563767336c544f6c4732466b773934625739686453564e576b4e77336358496a76452b0a49304b62445a3042394250776a4f556c4d55485954494e6f4d4969517870746c76704f6b465a492f6d4c794a6a35793071362f4c7a64386e68666159344a48580a58756f4b6b43467370483045576373726a5a576f6d4a396753677837794e787042354841787a35766569596f366e36396a686f35726c67386b57614e796e67470a386961724e68384876394e66635443752f494d4847345a6377415435592b2b41703141416a7049504746517947556e5746442f384d37594c57414664587a4c490a49414272437047714348566632466e4952644f6e58596b31445a77533539387975627a52694767624359477352784e515845745262755452427a366e4662614e0a4442444f5031597643317454673661395577434f774f695366586a592f534858594f5a3970774462593438344e632f564977527534504c2f2f7442634f396b430a746d646c5970394369384b416a6a41507669426b723571784a6178426c664f316457344a425a7a446b524a386a76756f35513675742b436b325956687a7056410a2b6d7562597a4f2b73652f745631486e724d47713950442f6c31355569694777696971306e553572386a4e75594f7547684e362b585745586163376866446a670a4c5342584b4531355350322b525a43536f4f52484551663156574b73367842463850484f2b7a324a35556c434c796468675466456a633466464a397368306a550a6f652f346e753252514f785a6a652b4e4f455636493537685a363974594b365a556d485a7930664f4c55306c73564950693356416930556d5850464e4f4a4c630a745463792b6b46524d5339506249314770553048776a744c4a544144534a6f6f315554366b44367770796f36365254612f7455686a4f6a5852624937336a504a0a3430626265515565646a686d2b364f50456a737977524330466f77377279724f633130507a317a5066436f70316e31494d6344504e484b7269786c2b32564d460a62454c587a4a466b624b4571652b757950365437426a49587437664a2f73646f683468356843537377797338634571527675616d504b57694747333444694a660a6c6d6556614d6b327961523756685746676848484a4547702f3033435a62715938306159532f6b7061612b62304458354f6b66642b4c37766d36684f724d48330a6275533948724a43334a2b796c4a306f66326854616445534b475753596e44347649505845596742353335492f533355755a596a465754525a4a78474e7263300a35494d47664247423065334733554a5055587a54366a2f687135424d326e69337439624956716773666878726f2b6e376b396f642f71394f50762b47744651610a73343953623143626b56393466577139536b7878644e2f4c47504e7270792b6d6d324767594c4a34577a302b6a536a7039716f614d71796a6c49376b6759696e0a3769537859504f6d764a67706539685330485751674d374e6864764a472f5241527757556a476f576e68514b4a486e4e39626841773962356e7154676d335a7a0a4330307a4d4139716c6a795179773448677a704c387854584c5947756a745850584b533874764e617977783967706933436c74682b487354773748514b31622b0a5173564757745639314151626d7a61554d59697375485167556d61626c66325938394744556668306a70367739483052704e624b4c7341306a76665354702b410a7764776a6d31452b31345a2f4a5a41346461487071595046794564626a6548333977516a386652792f4b48706d6c4b7851515845704837625a58363466514e540a2d2d2d2d2d454e44205253412050524956415445204b45592d2d2d2d2d0a*1766
$ssh2$2d2d2d2d2d424547494e20454e435259505445442050524956415445204b45592d2d2d2d2d0a4d494946446a424142676b71686b694739773042425130774d7a416242676b71686b694739773042425177774467514967554448624c57636d6c4943416767410a4d425147434371475349623344514d484241684c613754444438306b43415343424d6a6256676e45755837647534774257525358573050645a55335a747471610a77526b6e546834477a4752394759524a5a4271516e2f50512b327676576e33446a6873482b753468447252544b6b6a6b657659485a4c31364d4830646667774f0a7a583944792f4779305a6a51534d622f41524e625845356d6c50354c6f526657382f7838303147712f4a6a426936636461774a4d6b464a556b6571725837704d0a55364e41582b72315468766459665a3842504d31364c385250596e596c386a65425472584264557a56425650376f34726672685665314d7943655242763734370a55502b2f7432757a384f4b48444d43386e694261416d30324e61746577552f495769533241795445366c75636e792b384b427537626f53703538365547706a4f0a656c63456c69364974763558785636454a37554e304c69694a4d376f4a7a386346777a6f4f74545239325633654b712f5657537a6c462f4756684564765277330a4439452f49686f696f6b647977466a4b7a434246776a50496767576e4f3142586e3151573069657941626f6c6e5669716c694b36734b3143764667645465472f0a587855614b336671424657516579392b53616f34666771536a376941544a79394e4b78477079775a594b4b76456269614a394b55792f4442504b577932634a770a5377513645357468486752754a6f6f4647446735774857536b4f56716434334b2f32777955536a58383538524c734b346b53432f43624f744574584b76394f360a6561796d69417a4a7437423758497776675645582b4b636e374b32517134347a566d2f6d50634e315954646a736232796c386734625151585732305736714a570a7a306654366a69566c4f764932586557675871657a6d474b2f4d56346e796f6539433471534c592b5969427947772b7a33503641424464504c56345a453933490a6a706d786132454f444e583033395a7a3479466674397a48505044715957324e65704d484944584b757870415230464d413463502f4853367a536d4d6e6f31540a523033514f4531632f6c4c524545656d30314b327a576f794a46514a476f2f362f6a4a645854445758686754493739515a534d30666b784e52692b39444c54630a426552415945686c644c576d7356786849375958535638784d4c586b64382b696a6964346e785448706c456566437a484e6249784c4a366e33756e78366170330a72765750786366616e3044397239783657684a70766c424965324f476f5339515348436e7553504164687a767977657a70597247626634546c426733426d62510a44396455796e30514c334273513765673130664e6770707975646c6c4d7a4d5561496656334f4446577736486f574c5a394c746b3353356f577574582f326b750a324641676b5369394830416d564b7544556d4a57454e2b75414c4d6558534e503865797157647749314c534145344e4c78656c754162764e2f50306247574c490a686f614c427335554654546c53466943794d6b4d584b59757776704b6b75396f4f78494d704b5039424c65662b7a3634793272597849716955546d446f6833430a3447543932377056443558626d2f69463632335a4a324d6f62786c7a7563434d394d476c74434f635637394d555162596f4646713233774c6930536b334f79660a78425255394141686e30536e6635616b734941693837313346693733484b724b64754261794258392f716a2f6a6d326d62662f7051327a51734b302b306c77520a682b53416f3976417478316e4e715434497434666267397646714f736e62366977314851667073526e31374432567871476148506772597734704e68626e4d6e0a784b573744386d75496a386b46534d7169654d305455754e2b7351394270564b67477a616664313436634c6a536c4d65757861474378514b59665569704258760a49325964743679723476544957786a5754355470626f71426a51546d30565455766275386254372f68674f3461555235374b72424e4b79453643746e732f4d710a564763304758676c632f4437352b4f72452b6365573234596e4973643536356b32354a58434e4f52476175303458446552305449684b656a624b4e4f356b4d4c0a7362707934484563696c6b3478325171644673537a3944387a516b7476716861646c3179453359644958384941356246612f74543052522f54313656733166430a4a2b6c7676746636564c54396e3545625041504e46374c4265423443486974737a5579467369316f705642474367517161766e44502b43416a6b5739546f63480a5564413d0a2d2d2d2d2d454e4420454e435259505445442050524956415445204b45592d2d2d2d2d0a*1834*1
$ssh2$2d2d2d2d2d424547494e20454e435259505445442050524956415445204b45592d2d2d2d2d0a4d494943786a424142676b71686b694739773042425130774d7a416242676b71686b6947397730424251777744675149373033647571516237645943416767410a4d425147434371475349623344514d484241697455596c484854366e4a675343416f41314a656e6b4c56634236784c3671316a6255594a5038385a6a594541520a425775544d51524748675267787345785254494266513176664c4a4370676f556f4b6e526c59646f5973306262312b793856437348334e58446545512f444f6b0a37443036486a564c4543745435535741697a414d6b4a6545476f374a4e394432763947364a6a7571524c44732b6f423159467932556d587148326359396343560a5636413755375570387971416668416e4d4e6443523154445a6d354937594a4b32683630496a64797279576b474344545a624f4e554e5a4d4b7a326a62682f4b0a64486d61526833356531556f684d78535872725774696947316d485562375348445235664f446756677745356b4146615472763556757a7547743374535354550a5661447a584d59636c6f4e684832716a35694d784878647677374d72706a6d4b726672534c4c61583975687270316e512f4d3557547a7757776f42666c796c390a62685273354f5636792b4661702f4a6771737a416e55555a6a4e39503679514d555a5270464943636b41464145306b2b487a2b4332426453733679337a4978760a3371502b53366576685842696776616f3448462f30456830635062675643624e4b3947575245346f4b70662f54684b706938614173773855556c784f79466d630a4c46306843704270755344636a6e6362503956644b39564f5246574741795a7549754a342b724e63483036612b324a434763485852474c4f31794f4b505067410a764a55336b2f385669424d454168436e76344a5648374637446a47674d496a636d6c7148654a2b4a3435465233516f6c31416b4b434c2f33374e6469314575590a73716a55565759385445492f42785a6946384d77372b74664f48765655497873356a537a2f535a367142757657306a5a6978634c4f7375757a30665a656a4b560a6c35694f6230754b45464b6d4e3346434e77412f54783143564744356d6f422f42416d384f6f316a4c475a446b74456d65527463594534714e793471634632570a3667734c6a357074634278774548745a3733316e4f55436c327548327630694165716231394f45326b454f58526979503439476e73622f58374349724a3076760a7130506e7a644a5a30345a3445727675762b724e4f323676513662496d73534b6b5336505741516e4c57304b562b355a676e596b514561320a2d2d2d2d2d454e4420454e435259505445442050524956415445204b45592d2d2d2d2d0a*1041*1
```
$ ./john pwfile
```C
Segmentation fault
```

# 2. GDB debug

```C
Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:157
157	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:157
#1  0x00000000005ce214 in ldr_load_pw_line (db=<optimized out>, line=<optimized out>) at loader.c:914
#2  0x00000000005cbba1 in read_file (db=0xfac1c0 <database>, name=0x10ca118 "out_no_asan/crashes/id:000095,sig:11,src:000109,op:flip1,pos:28", flags=<optimized out>,
    process_line=0x5cdae0 <ldr_load_pw_line>) at loader.c:135
#3  0x00000000005c9f5a in john_load () at john.c:1006
#4  0x00000000005ca7f5 in john_init (name=0x7fffffffec04 "john", argc=2, argv=0x7fffffffe968) at john.c:1290
#5  0x00000000005cb4e6 in main (argc=2, argv=0x7fffffffe968) at john.c:1730
```

**Comment by jfoug** [comment]
Fixed in a20dc43
