### ISSUE TITLE
oldoffice_fmt: ASAN: heap-buffer-overflow

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1410]
This bug is found by afl.

# 1. Reproduce

$  ./configure --enable-asan && make -sj8
$ cat pwfile
```
$oldoffice$3*de17a7f3c3ff03a39937ba9666d6e952*2374d5b6ce7449f57c9f252f9f9b53d2*e60e1185f7aecedba262f869c0236f81
$oldoffice$0*e40b4fdade5be6be329c4238e2099b8a*259590322b55f7a3c38cb96b5864e72d*2e6516bfaf981770fe6819a34998295d
$oldoffice$1*d6aabb63363188b9b73a88efb9c9152e*afbbb9254764273f8f4fad9a5d82981f*6f09fd2eafc4ade522b5f2bee0eaf66d*f2ab1219ae
$oldoffice$3*9f32522fe9bcb69b12f39d3c24b39b2f*fac8b91a8a578468ae7001df4947558f*f2e267a5bea45736b52d6d1051eca1b935eabf3a
$oldoffice$3*095b777a73a10fb6bcd3e48d50f8f8c5*36902daab0d0f38f587a84b24bd40dce*25db453f79e8cbe4da1844822b88f6ce18a5edd2
$oldoffice$3*284bc91cb64bc847a7a44bc7bf34fb69*1f8c589c6fcbd43c42b2bc6fff4fd12b*2bc7d8e866c9ea40526d3c0a59e2d37d8ded3550
$oldoffice$4*a58b39c30a06832ee664c1db48d17304*986a45cc9e17e062f05ceec37ec0db17*fe0c130ef374088f3fec1979aed4d67459a6eb9a
$oldoffice$3*f426041b2eba9745d30c7949801f7d3a*888b34927e5f31e2703cc4ce86a6fd78*ff66200812fd06c1ba43ec2be9f3390addb20096
$oldoffice$3*DB575DDA2E450AB3DFDF77A2E9B3D4C7*AB183C4C8B5E5DD7B9F3AF8AE5FFF31A*B63594447FAE7D4945D2DAFD113FD8C9F6191BF5
$oldoffice$3*3fbf56a18b026e25815cbea85a16036c*216562ea03b4165b54cfaabe89d36596*91308b40297b7ce31af2e8c57c6407994b205590
```
$ ./john pwfile
```C
=================================================================
==92809==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60b00000af50 at pc 0x657775 bp 0x7ffd1d295ee0 sp 0x7ffd1d295ed8
READ of size 1 at 0x60b00000af50 thread T0
    #0 0x657774 in get_salt /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/oldoffice_fmt_plug.c:208
    #1 0x748c53 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:897
    #2 0x749c96 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #3 0x74c67f in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1000
    #4 0x73fecc in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1006
    #5 0x74162b in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1290
    #6 0x7431d2 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1730
    #7 0x7fadfce3fec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #8 0x407032 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john+0x407032)

0x60b00000af50 is located 0 bytes to the right of 112-byte region [0x60b00000aee0,0x60b00000af50)
allocated by thread T0 here:
    #0 0x7fadfe61a7df in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x547df)
    #1 0x7fadfcea6839 in strdup (/lib/x86_64-linux-gnu/libc.so.6+0x88839)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/oldoffice_fmt_plug.c:208 get_salt
Shadow bytes around the buggy address:
  0x0c167fff9590: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff95a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff95b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff95c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff95d0: fa fa fa fa fa fa fa fa fa fa fa fa 00 00 00 00
=>0x0c167fff95e0: 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa
  0x0c167fff95f0: fa fa fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c167fff9600: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff9610: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff9620: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c167fff9630: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==92809==ABORTING
Aborted
```

# 2. GDB debug

```C
Program received signal SIGABRT, Aborted.
0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff57940d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f640e9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#3  0x00007ffff6f5bde5 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#4  0x00007ffff6f5fbe2 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#5  0x00007ffff6f5b279 in __asan_report_error () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#6  0x00007ffff6f5c0c4 in __asan_report_load1 () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#7  0x0000000000657775 in get_salt (ciphertext=<optimized out>) at oldoffice_fmt_plug.c:208
#8  0x0000000000748c54 in ldr_load_pw_line (db=db@entry=0x1291040 <database>, line=<optimized out>) at loader.c:897
#9  0x0000000000749c97 in read_file (db=db@entry=0x1291040 <database>, name=name@entry=0x631000000868 "out_asan/crashes/id:000118", flags=flags@entry=2,
    process_line=process_line@entry=0x7482a6 <ldr_load_pw_line>) at loader.c:135
#10 0x000000000074c680 in ldr_load_pw_file (db=0x1291040 <database>, name=0x631000000868 "out_asan/crashes/id:000118") at loader.c:1000
#11 0x000000000073fecd in john_load () at john.c:1006
#12 0x000000000074162c in john_init (name=0x7fffffffec29 "john", argc=2, argv=0x7fffffffe998) at john.c:1290
#13 0x00000000007431d3 in main (argc=2, argv=0x7fffffffe998) at john.c:1730
```

**Comment by jfoug** [comment]
Needs put into opencl also.
