### ISSUE TITLE
pbkdf2-hmac-sha512-opencl: Abort trap: 6

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1476]
$ CC=clang ./configure --enable-opencl && make -sj8
$ cat pwfile
```
grub.pbkdf2.sha512.10000.4483972AD2C52E1F590B3E2260795FDA9CA0B07B96FF492814CA9775F08C4B59CD1707F10B269E09B61B1E2D11729BCA8D62B7827B25B093EC58C4C1EAC23137.DF4FCB5DD91340D6D31E33423E4210AD47C7A4DF9FA16F401663BF288C20BF973530866178FE6D134256E4DBEFBD984B652332EED3ACAED834FEA7B73CAE851DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
grub.pbkdf2.sha512.10000.4483972AD2C52E1F590B3E2260795FDA9CA0B07B96FF492814CA9775F08C4B59CD1707F10B269E09B61B1E2D11729BCA8D62B7827B25B093EC58C4C1EAC23137.DF4FCB5DD91340D6D31E33423E4210AD47C7A4DF9FA16F401663BF288C20BF973530866178FE6D134256E4DBEFBD984B652332EED3ACAED834FEA7B73CAE851DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
```
$ ./john pwfile
```
Warning: detected hash type "PBKDF2-HMAC-SHA512", but the string is also recognized as "pbkdf2-hmac-sha512-opencl"
Use the "--format=pbkdf2-hmac-sha512-opencl" option to force loading these as that type instead
Abort trap: 6
```

**Comment by jfoug** [comment]
Strange bug:

```
$ /JtR/bleed/run/john
John the Ripper 1.8.0.6-jumbo-1-166-gf4e5114+ OMP ASan [linux-gnu 64-bit SSE4.1-autoconf]
Copyright (c) 1996-2015 by Solar Designer and others

$ /JtR/bleed/run/john in
Using default input encoding: UTF-8
Loaded 1 password hash (PBKDF2-HMAC-SHA512, GRUB2 / OS X 10.8+ [PBKDF2-SHA512 128/128 SSE4.1 2x])
Will run 4 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status

PBKDF2-HMAC-SHA512: Warning: Partial match for 'password'.
This is a bug or a malformed input line of:
$pbkdf2-hmac-sha512$10000.4483972ad2c52e1f590b3e2260795fda9ca0b07b96ff492814ca9775f08c4b59cd1707f10b269e09b61b1e2d11729bca8d62b7827b25b093ec58c4c1eac23137.df4fcb5dd91340d6d31e33423e4210ad47c7a4df9fa16f401663bf288c20bf973530866178fe6d134256e4dbefbd984b652332eed3acaed834fea7b73cae851ddddddddddddddddddddddddddddddddddddddddddd

PBKDF2-HMAC-SHA512: Warning: Partial match for 'password'.
This is a bug or a malformed input line of:
$pbkdf2-hmac-sha512$10000.4483972ad2c52e1f590b3e2260795fda9ca0b07b96ff492814ca9775f08c4b59cd1707f10b269e09b61b1e2d11729bca8d62b7827b25b093ec58c4c1eac23137.df4fcb5dd91340d6d31e33423e4210ad47c7a4df9fa16f401663bf288c20bf973530866178fe6d134256e4dbefbd984b652332eed3acaed834fea7b73cae851ddddddddddddddddddddddddddddddddddddddddddd
```

I have no clang to test with.

**Comment by magnumripper** [comment]
I get the exact same abort trap as Kai, using gcc 4.9.2

A stack trace tells a lot more.
```
Program received signal SIGABRT, Aborted.
0x00007fff953cc286 in __pthread_kill ()
(gdb) bt
#0  0x00007fff953cc286 in __pthread_kill ()
#1  0x00007fff9643642f in pthread_kill ()
#2  0x00007fff90b48b53 in abort ()
#3  0x00007fff90b48cca in abort_report_np ()
#4  0x00007fff90b6edb0 in __chk_fail ()
#5  0x00007fff90b6ed80 in __chk_fail_overflow ()
#6  0x00007fff90b6eef8 in __strncat_chk ()
#7  0x000000010019472d in prepare (split_fields=0x0, self=0x10043c880) at opencl_pbkdf2_hmac_sha512_fmt_plug.c:302
Previous frame inner to this frame (gdb could not unwind past this frame)
```

**Comment by magnumripper** [comment]
I guess someone fixed the bug already in the CPU format, and missed the OpenCL one.

**Comment by magnumripper** [comment]
Some/all of 5391a515, c0cdf191 and b6febb7495 may need to be applied to OpenCL format too.

**Comment by magnumripper** [comment]
```
PBKDF2-HMAC-SHA512: Warning: Partial match for 'password'.
This is a bug or a malformed input line of:
$pbkdf2-hmac-sha512$10000.4483972ad2c52e1f590b3e2260795fda9ca0b07b96ff492814ca9775f08c4b59cd1707f10b269e09b61b1e2d11729bca8d62b7827b25b093ec58c4c1eac23137.df4fcb5dd91340d6d31e33423e4210ad47c7a4df9fa16f401663bf288c20bf973530866178fe6d134256e4dbefbd984b652332eed3acaed834fea7b73cae851ddddddddddddddddddddddddddddddddddddddddddd
```
This is expected behavior. The input line is indeed malformed, but we do crack it when only considering the first limb of PBKDF2. So we complain and keep going.
