### ISSUE TITLE
Undefined behavior / illegal instruction for RAR5 format (ASan+UbSan build)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1493]
```
$ cat fail_RAR5.pw 
$rar5$16$92373e6493111cf1f2443dcd82122af9$-15$011a3192b2f637d43deba9d0a08b7fa0$8$6862fcec47944d14
$ cat fail.lst     
12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345
$ ./john fail_RAR5.pw --wordlist=fail.lst 
Illegal instruction
$ gdb ./john 
[...]
(gdb) run fail_RAR5.pw --wordlist=fail.lst
Starting program: /home/fd/git/JtR/run/john fail_RAR5.pw --wordlist=fail.lst
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//lib64/libfreebl3.so.debug" does not match "/lib64/libfreebl3.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libfreebl3.so.debug" does not match "/lib64/libfreebl3.so" (CRC mismatch).


Program received signal SIGILL, Illegal instruction.
0x00000000006a3596 in get_salt (ciphertext=<optimized out>) at rar5_common.h:128
128		cs.iterations = 1 << atoi(p);
Missing separate debuginfos, use: dnf debuginfo-install gmp-6.0.0-9.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-3.fc22.x86_64 libasan-5.1.1-4.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libgcc-5.1.1-4.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.1.1-4.fc22.x86_64 libubsan-5.1.1-4.fc22.x86_64 nss-softokn-freebl-3.19.2-1.0.fc22.x86_64 openssl-libs-1.0.1k-10.fc22.x86_64 pcre-8.37-1.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) bt
#0  0x00000000006a3596 in get_salt (ciphertext=<optimized out>) at rar5_common.h:128
#1  0x0000000000753f64 in ldr_load_pw_line (db=db@entry=0xfbd180 <database>, line=<optimized out>) at loader.c:897
#2  0x0000000000754f63 in read_file (db=db@entry=0xfbd180 <database>, name=name@entry=0x631000014868 "fail_RAR5.pw", flags=flags@entry=2, 
    process_line=process_line@entry=0x753629 <ldr_load_pw_line>) at loader.c:135
#3  0x0000000000757faf in ldr_load_pw_file (db=0xfbd180 <database>, name=0x631000014868 "fail_RAR5.pw") at loader.c:1000
#4  0x000000000074b8a1 in john_load () at john.c:1021
#5  0x000000000074d3ba in john_init (name=0x7fffffffe3a6 "john", argc=3, argv=0x7fffffffe098) at john.c:1305
#6  0x000000000074efbc in main (argc=3, argv=0x7fffffffe098) at john.c:1743
```

When I rebuild john, but without `-fsanitize-undefined-trap-on-error` in the CFLAGS, I get
```
$ ./john fail_RAR5.pw --wordlist=fail.lst
rar5_common.h:128:20: runtime error: shift exponent -15 is negative
Using default input encoding: UTF-8
Loaded 1 password hash (RAR5 [PBKDF2-SHA256 256/256 AVX2 8x])
Press 'q' or Ctrl-C to abort, almost any other key for status
0g 0:00:00:00 DONE (2015-07-04 20:57) 0g/s 2.564p/s 2.564c/s 2.564C/s 12345678901234567890123456789012
Session completed
```

**Comment by magnumripper** [comment]
You need to state if your example hash is a fake/fuzzed "bad input" or a real one that should not fail.

**Comment by frank-dittrich** [comment]
It came up when I was fuzzing, so I assume it is invalid.

**Comment by magnumripper** [comment]
So this is just a case of promiscuous valid()
