### ISSUE TITLE
sha1crypt_common_plug.c:51  Asan  heap-buffer-overflow

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1552]
# 1. Reproduce

$ cat pwfile
```
$sha1$94000$wnUR8T1U$vt1TFQ50tBMFgkflAFAOer2CwdYZ
```
$ ./configure --enable-asan && make -sj8
$ ./john pwfile
```
=================================================================
==17349==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60600000eff2 at pc 0x56713f bp 0x7ffe59d9e5a0 sp 0x7ffe59d9e598
READ of size 1 at 0x60600000eff2 thread T0
    #0 0x56713e in base64_valid_length /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/base64_convert.c:1118
    #1 0x8bc778 in sha1crypt_common_valid /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/sha1crypt_common_plug.c:51
    #2 0x94f4ec in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:717
    #3 0x94fe94 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:821
    #4 0x94b503 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #5 0x951e4e in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1019
    #6 0x94758c in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1023
    #7 0x948ceb in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1307
    #8 0x94a8b3 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1748
    #9 0x7fa5e0a38ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #10 0x406de8 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john+0x406de8)

0x60600000eff2 is located 0 bytes to the right of 50-byte region [0x60600000efc0,0x60600000eff2)
allocated by thread T0 here:
    #0 0x7fa5e21f1937 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x32937)
    #1 0x8bc432 in sha1crypt_common_valid /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/sha1crypt_common_plug.c:33
    #2 0x94f4ec in ldr_split_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:717
    #3 0x94fe94 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:821
    #4 0x94b503 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #5 0x951e4e in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1019
    #6 0x94758c in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1023
    #7 0x948ceb in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1307
    #8 0x94a8b3 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1748
    #9 0x7fa5e0a38ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/base64_convert.c:1118 base64_valid_length
Shadow bytes around the buggy address:
  0x0c0c7fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9db0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9dc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9dd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9de0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c0c7fff9df0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00[02]fa
  0x0c0c7fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c7fff9e40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==17349==ABORTING
Aborted (core dumped)
```

# 2. gdb Debug

```C
Program received signal SIGABRT, Aborted.
0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff57940d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f640e9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#3  0x00007ffff6f5bde5 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#4  0x00007ffff6f5fbe2 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#5  0x00007ffff6f5b279 in __asan_report_error () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#6  0x00007ffff6f5c0c4 in __asan_report_load1 () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#7  0x000000000056713f in base64_valid_length (from=0x60600000eff2 "", from_t=e_b64_crypt, flags=0) at base64_convert.c:1118
#8  0x00000000008bc779 in sha1crypt_common_valid (ciphertext=0x7ffffffce690 "$sha1$94000$wnUR8T1U$vt1TFQ50tBMFgkflAFAOer2CwdYZ", self=0xe66280 <fmt_cryptsha1>)
    at sha1crypt_common_plug.c:51
#9  0x000000000094f4ed in ldr_split_line (login=0x7ffffffce3f0, ciphertext=0x7ffffffce430, gecos=0x7ffffffce470, home=0x7ffffffce4b0, uid=0x7ffffffce4f0, source=0x0,
    format=0x1225ee8 <database+104>, db_opts=0x63100038fe00, line=0x0) at loader.c:717
#10 0x000000000094fe95 in ldr_load_pw_line (db=0x1225e80 <database>, line=0x7ffffffce690 "$sha1$94000$wnUR8T1U$vt1TFQ50tBMFgkflAFAOer2CwdYZ") at loader.c:821
#11 0x000000000094b504 in read_file (db=0x1225e80 <database>, name=0x631000000868 "err_pwfiles/pwfile.sha1crypt", flags=2, process_line=0x94fd2d <ldr_load_pw_line>)
    at loader.c:135
#12 0x0000000000951e4f in ldr_load_pw_file (db=0x1225e80 <database>, name=0x631000000868 "err_pwfiles/pwfile.sha1crypt") at loader.c:1019
#13 0x000000000094758d in john_load () at john.c:1023
#14 0x0000000000948cec in john_init (name=0x7fffffffec2e "john", argc=2, argv=0x7fffffffe998) at john.c:1307
#15 0x000000000094a8b4 in main (argc=2, argv=0x7fffffffe998) at john.c:1748
(gdb)
```

**Comment by jfoug** [comment]
Please retest this after 6c8cde9  I think it is fixed.

**Comment by loverszhaokai** [comment]
Thanks. Fixed.
