### ISSUE TITLE
dynamic_fmt.c:2003  Asan  unknown-crash

### ISSUE THREAD

**Issue by loverszhaokai** [magnumripper/JohnTheRipper#1554]
# 1. Reproduce

## pwfile
```
The pwfile is too large to display here. It is already minized. 
Here is the link: https://raw.githubusercontent.com/loverszhaokai/Cloud/master/John/dynamic_2001_failed_pw
```
$ ./configure --enable-asan && make -sj8
$ ./john pwfile
```
Warning: invalid UTF-8 seen reading pwfile
=================================================================
==86914==ERROR: AddressSanitizer: unknown-crash on address 0x7fe530b7c777 at pc 0x5808a8 bp 0x7ffd523c8260 sp 0x7ffd523c8258
READ of size 138 at 0x7fe530b7c777 thread T0
    #0 0x5808a7 in FindSaltHash /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2003
    #1 0x5809fb in HashSalt /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2021
    #2 0x58592b in get_salt /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2343
    #3 0x950b51 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:916
    #4 0x94b503 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #5 0x951e4e in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1019
    #6 0x94758c in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1023
    #7 0x948ceb in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1307
    #8 0x94a8b3 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1748
    #9 0x7fe535ad9ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #10 0x406de8 (/home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/run/john+0x406de8)

0x7fe530b7c800 is located 0 bytes to the right of 393216-byte region [0x7fe530b1c800,0x7fe530b7c800)
allocated by thread T0 here:
    #0 0x7fe5372b47df in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x547df)
    #1 0x96fb4e in mem_alloc_func /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/memory.c:89
    #2 0x96fdae in mem_alloc_tiny_func /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/memory.c:196
    #3 0x5802c1 in AddSaltHash /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:1969
    #4 0x58073b in FindSaltHash /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:1998
    #5 0x5809fb in HashSalt /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2021
    #6 0x58592b in get_salt /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2343
    #7 0x950b51 in ldr_load_pw_line /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:916
    #8 0x94b503 in read_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:135
    #9 0x951e4e in ldr_load_pw_file /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/loader.c:1019
    #10 0x94758c in john_load /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1023
    #11 0x948ceb in john_init /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1307
    #12 0x94a8b3 in main /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/john.c:1748
    #13 0x7fe535ad9ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

SUMMARY: AddressSanitizer: unknown-crash /home/zhaokai/WorkSpace/open_wall/JohnTheRipper_kai/src/dynamic_fmt.c:2003 FindSaltHash
Shadow bytes around the buggy address:
  0x0ffd26167890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd261678a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd261678b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd261678c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd261678d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ffd261678e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00[00]00
  0x0ffd261678f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd26167900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd26167910: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd26167920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd26167930: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
==86914==ABORTING
Aborted (core dumped)
```

# 2. gdb Debug

```C
(gdb) bt
#0  0x00007ffff5790cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff57940d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6f640e9 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#3  0x00007ffff6f5bde5 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#4  0x00007ffff6f5fbe2 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#5  0x00007ffff6f5b279 in __asan_report_error () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#6  0x00007ffff6f5c2a1 in __asan_report_load_n () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#7  0x00000000005808a8 in FindSaltHash (salt=0x7ffffffcdd30 "@400001aDNNojYGSc7pSzcdxKxhbqvLtE", '$' <repeats 100 times>, "e4deG\336\367\377\177", len=138, crc=3826882950)
    at dynamic_fmt.c:2003
#8  0x00000000005809fc in HashSalt (salt=0x7ffffffcdd30 "@400001aDNNojYGSc7pSzcdxKxhbqvLtE", '$' <repeats 100 times>, "e4deG\336\367\377\177", len=138)
    at dynamic_fmt.c:2021
#9  0x000000000058592c in get_salt (
    ciphertext=0xf4ee40 <out> "$dynamic_2001$ed52af63d8ecf0c682442dfef5f36391$1aDNNojYGSc7pSzcdxKxhbqvLtE", '$' <repeats 100 times>, "e4deG") at dynamic_fmt.c:2343
#10 0x0000000000950b52 in ldr_load_pw_line (db=0x1225e80 <database>,
    line=0x7ffffffce6a0 "$dynamic_2001$ed52af63d8ecf0c682442dfef5f36391$1aDNNojYGSc7pSzcdxKxhbqvLtE", '$' <repeats 100 times>, "e4deG") at loader.c:916
#11 0x000000000094b504 in read_file (db=0x1225e80 <database>, name=0x631000000868 "pwfile", flags=2, process_line=0x94fd2d <ldr_load_pw_line>) at loader.c:135
#12 0x0000000000951e4f in ldr_load_pw_file (db=0x1225e80 <database>, name=0x631000000868 "pwfile") at loader.c:1019
#13 0x000000000094758d in john_load () at john.c:1023
#14 0x0000000000948cec in john_init (name=0x7fffffffec3f "john", argc=2, argv=0x7fffffffe9a8) at john.c:1307
#15 0x000000000094a8b4 in main (argc=2, argv=0x7fffffffe9a8) at john.c:1748
(gdb)
```

**Comment by jfoug** [comment]
Another very good catch.
