### ISSUE TITLE
LM-opencl benchmarked twice ??

### ISSUE THREAD

**Issue by Sayantan2048** [magnumripper/JohnTheRipper#1588]
This bug was introduced with bc53b4ae6e7b9e69.  
```
./john -te -format=lm-opencl
NOTE: This is a debug build, speed will be lower than normal
Device 0: Tahiti [AMD Radeon R9 200 / HD 7900 Series]
Benchmarking: LM-opencl [DES BS OpenCL]... DONE
Raw:    36177K c/s real, 41812K c/s virtual

Benchmarking: LM-opencl [DES BS OpenCL]... ASAN:SIGSEGV
=================================================================
==27635==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x00000071dad3 sp 0x7fff1c34c9a0 bp 0x7fff1c34c9c0 T0)
    #0 0x71dad2 in reset /home/sayantan/JtRCurrent/src/opencl_lm_b_plug.c:729
    #1 0x87fcc5 in fmt_self_test_body /home/sayantan/JtRCurrent/src/formats.c:295
    #2 0x882e19 in fmt_self_test /home/sayantan/JtRCurrent/src/formats.c:719
    #3 0x868008 in benchmark_format /home/sayantan/JtRCurrent/src/bench.c:235
    #4 0x869ce6 in benchmark_all /home/sayantan/JtRCurrent/src/bench.c:652
    #5 0x890ce2 in john_run /home/sayantan/JtRCurrent/src/john.c:1368
    #6 0x892121 in main /home/sayantan/JtRCurrent/src/john.c:1741
    #7 0x7f1846b5f76c in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2176c)
    #8 0x407d74 (/home/sayantan/JtRCurrent/run/john+0x407d74)
```
Somehow we're re entering reset with database pointing at invalid location. Note that  john is run just once.

**Comment by Sayantan2048** [comment]
Fixed c0560a42f85c437c7b96819
