### ISSUE TITLE
CUDA segfault when NVML not available

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1630]
@dm0 reported in https://github.com/magnumripper/JohnTheRipper/pull/1624#issuecomment-129171315
>  jtr segfaults during opencl initialization. (Cuda 5.0, tesla m2090).

```
$ gdb ../run/john
GNU gdb (GDB) CentOS (7.0.1-45.el5.centos)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /sfsdata/home/dmitri/recovery/jtr-fix/JohnTheRipper-bleeding-jumbo/run/john...done.
(gdb) r --list=opencl-devices
Starting program: /sfsdata/home/dmitri/recovery/jtr-fix/JohnTheRipper-bleeding-jumbo/run/john --list=opencl-devices
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x2aaaaaaab000
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000006ab8ba in id2nvml (busInfo=...) at common-gpu.c:409
#2  0x00000000007009e5 in start_opencl_device (sequential_id=0, err_type=0x7fffffff9d3c) at common-opencl.c:470
#3  0x0000000000701c8d in add_device_to_list (sequential_id=0) at common-opencl.c:551
#4  0x0000000000702379 in build_device_list () at common-opencl.c:603
#5  opencl_preinit () at common-opencl.c:727
#6  0x00000000006e5bd4 in listconf_parse_early () at listconf.c:333
#7  0x00000000006bfe9f in john_init (name=0x7fffffffeb33 "john", argc=2, argv=0x7fffffffe8d8) at john.c:1251
#8  0x00000000006c0fe0 in main (argc=2, argv=0x7fffffffe8d8) at john.c:1728
(gdb) frame 1
#1  0x00000000006ab8ba in id2nvml (busInfo=...) at common-gpu.c:409
409			if (nvmlDeviceGetIndex(dev, &id_NVML) == NVML_SUCCESS)
(gdb) generate-core-file
warning: Memory read failed for corefile section, 4096 bytes at 0x2aaaaaab0000.
warning: Memory read failed for corefile section, 4096 bytes at 0x2aaaab15f000.
Saved corefile core.1521
```

Please find the mentioned `core.1521` here: https://dl.dropboxusercontent.com/u/1920141/core.1521
I also saved ./configure output (I don't know if it contains any useful information): https://dl.dropboxusercontent.com/u/1920141/jtr-configure.log

I guess that the problem is somehow related to temperature sensors (nvidia-smi shows N/A for temperature and fans):

```
$ nvidia-smi
Sun Aug  9 21:38:37 2015
+------------------------------------------------------+
| NVIDIA-SMI 4.304.54   Driver Version: 304.54         |
|-------------------------------+----------------------+----------------------+
| GPU  Name                     | Bus-Id        Disp.  | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap| Memory-Usage         | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M2090              | 0000:24:00.0     Off |                    0 |
| N/A   N/A    P0   177W / 225W |   5%  270MB / 5375MB |     91%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by magnumripper** [comment]
Please reopen if 7276112 did not fix it. Thanks for reporting.
