### ISSUE TITLE
Regression problem from john-huge-prefetch.diff

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1771]
I get a segfault (after a while, and after cracking a good number) using single mode with LM. Bisected it to a2294f9f which is john-huge-prefetch.diff. So I tried just defining CRK_PREFETCH to 0 in current code - and problem goes away. 
```
Program received signal SIGSEGV, Segmentation fault.
DES_bs_cmp_one (binary=0x0, count=64, index=6) at DES_bs.c:531
531		CMP_BIT(30);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.7.x86_64 gmp-4.3.1-7.el6_2.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-37.el6_6.x86_64 libcom_err-1.41.12-21.el6.x86_64 libgomp-4.4.7-11.el6.x86_64 libselinux-2.0.94-5.8.el6.x86_64 nss-softokn-freebl-3.14.3-22.el6_6.x86_64 openssl-1.0.1e-30.el6_6.11.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  DES_bs_cmp_one (binary=0x0, count=64, index=6) at DES_bs.c:531
#1  0x00000000006f91e2 in crk_password_loop (salt=0x13ad628) at cracker.c:818
#2  0x00000000006f9901 in crk_process_salt (salt=0x13ad628) at cracker.c:955
#3  0x000000000071ee3c in single_process_buffer (salt=0x13ad628) at single.c:260
#4  0x000000000071ff37 in single_process_pw (db=<value optimized out>) at single.c:326
#5  single_process_salt (db=<value optimized out>) at single.c:398
#6  single_run (db=<value optimized out>) at single.c:483
#7  do_single_crack (db=<value optimized out>) at single.c:538
#8  0x0000000000704848 in john_run () at john.c:1589
#9  0x0000000000705002 in main (argc=4, argv=0x7fffffffe3f8) at john.c:1879
```
Committed the workaround in b45a632c

**Comment by magnumripper** [comment]
http://www.openwall.com/lists/john-dev/2015/09/20/6
