### ISSUE TITLE
Floating point exception (core dumped) in common-opencl.c:1213

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1776]
Testinf the latest beignet commit with my Haswell CPU:

```
(gdb) run --test --format=sha256crypt-opencl
[...]
Program received signal SIGFPE, Arithmetic exception.
0x000000000070f136 in gws_test (gws=gws@entry=1024, rounds=rounds@entry=5000, sequential_id=<optimized out>) at common-opencl.c:1213
1213			runtime += (looptime * rounds) / (hash_loops * total);
Missing separate debuginfos, use: dnf debuginfo-install expat-2.1.0-10.fc22.x86_64 gmp-6.0.0-9.fc22.x86_64 keyutils-libs-1.5.9-4.fc22.x86_64 krb5-libs-1.13.2-5.fc22.x86_64 libcom_err-1.42.12-4.fc22.x86_64 libdrm-2.4.61-3.fc22.x86_64 libedit-3.1-12.20150325cvs.fc22.x86_64 libffi-3.1-7.fc22.x86_64 libgcc-5.1.1-4.fc22.x86_64 libgomp-5.1.1-4.fc22.x86_64 libicu-54.1-1.fc22.x86_64 libpciaccess-0.13.3-0.3.fc22.x86_64 libselinux-2.3-10.fc22.x86_64 libstdc++-5.1.1-4.fc22.x86_64 libX11-1.6.3-1.fc22.x86_64 libXau-1.0.8-4.fc22.x86_64 libxcb-1.11-8.fc22.x86_64 libXdamage-1.1.4-6.fc22.x86_64 libXext-1.3.3-2.fc22.x86_64 libXfixes-5.0.1-4.fc22.x86_64 libxshmfence-1.2-1.fc22.x86_64 libXxf86vm-1.1.4-1.fc22.x86_64 mesa-libGL-10.6.3-1.20150729.fc22.x86_64 mesa-libglapi-10.6.3-1.20150729.fc22.x86_64 ncurses-libs-5.9-18.20150214.fc22.x86_64 nss-softokn-freebl-3.20.0-1.0.fc22.x86_64 ocl-icd-2.2.3-1.git20141005.7cd0c2f.fc22.x86_64 openssl-libs-1.0.1k-12.fc22.x86_64 pcre-8.37-4.fc22.x86_64 zlib-1.2.8-7.fc22.x86_64
(gdb) bt
#0  0x000000000070f136 in gws_test (gws=gws@entry=1024, rounds=rounds@entry=5000, sequential_id=<optimized out>) at common-opencl.c:1213
#1  0x0000000000710c14 in opencl_find_best_gws (step=0, max_run_time=<optimized out>, sequential_id=0, rounds=rounds@entry=5000, have_lws=<optimized out>) at common-opencl.c:1528
#2  0x00000000007173fa in autotune_find_best_gws (sequential_id=<optimized out>, rounds=rounds@entry=5000, step=<optimized out>, step@entry=0, max_run_time=<optimized out>, 
    have_lws=<optimized out>) at opencl_autotune.c:96
#3  0x00000000005bc568 in find_best_gws (have_lws=<optimized out>, max_run_time=<optimized out>, rounds=5000, sequential_id=<optimized out>, self=0xb0f620 <fmt_opencl_cryptsha256>)
    at opencl-autotune.h:84
#4  autotune_run_extra (rounds=5000, gws_limit=0, lws_is_power_of_two=0, max_run_time=<optimized out>, self=0xb0f620 <fmt_opencl_cryptsha256>) at opencl-autotune.h:187
#5  autotune_run (max_run_time=<optimized out>, gws_limit=0, rounds=5000, self=0xb0f620 <fmt_opencl_cryptsha256>) at opencl-autotune.h:226
#6  reset (db=<optimized out>) at opencl_cryptsha256_fmt_plug.c:320
#7  0x00000000006c500b in fmt_self_test_body (db=0x0, salt_copy=0x109b804, binary_copy=0x109b7d4, format=0xb0f620 <fmt_opencl_cryptsha256>) at formats.c:398
#8  fmt_self_test (format=format@entry=0xb0f620 <fmt_opencl_cryptsha256>, db=db@entry=0x0) at formats.c:1483
#9  0x00000000006b9359 in benchmark_format (format=0xb0f620 <fmt_opencl_cryptsha256>, salts=256, results=0x7fffffffd520) at bench.c:239
#10 0x00000000006ba1d2 in benchmark_all () at bench.c:653
#11 0x00000000006ce21a in john_run () at john.c:1491
#12 0x00000000006ced85 in main (argc=3, argv=0x7fffffffdfd8) at john.c:1880
```

Values of involved variables:
total:0
hash_loops:168
rounds:5000
looptime:0

**Comment by magnumripper** [comment]
Try with fede4e1. I'm not quite sure what happened but at least we should not divide by zero now.

**Comment by frank-dittrich** [comment]
Self test passes with commit fede4e1
```
$ time ./john --test --format=sha256crypt-opencl --verbosity=5
initUnicode(UNICODE, ASCII/ASCII)
ASCII -> ASCII -> ASCII
Benchmarking: sha256crypt-opencl, crypt(3) $5$ (rounds=5000) [SHA256 OpenCL]... Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Failed to release test userptr object! (9) i915 kernel driver may not be sane!
Device 0: Intel(R) HD Graphics Haswell GT2 Desktop
Options used: -I ./kernels -cl-mad-enable -D__GPU__ -DDEVICE_INFO=34 -DDEV_VER_MAJOR=1 -DDEV_VER_MINOR=2 -D_OPENCL_COMPILER 
Calculating best GWS for LWS=32; max. 150ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 161.462ms* (exceeds 150ms)
Calculating best LWS for GWS=32
Testing LWS=32 GWS=32 ... 46.972ms+
Testing LWS=64 GWS=64 ...OpenCL CL_INVALID_VALUE error in opencl_cryptsha256_fmt_plug.c:403 - failed in reading data back
Calculating best GWS for LWS=32; max. 300ms single kernel invocation.
Raw speed figures including buffer transfers:
pass xfer: 104.398ms*, crypt: 29x23.834ms, result xfer: 18.933ms*, prepare: 5.917ms, final: 18.869ms, mean: 23.852ms/23.799ms
gws:       640	       746 c/s     3730000 rounds/s 857.314ms per crypt_all()!
pass xfer: 210.297ms*, crypt: 29x52ms, result xfer: 40.807ms*, prepare: 13.800ms, final: 40.751ms, mean: 51.346ms/51.942ms
gws:      1280	       693 c/s     3465000 rounds/s    1.846s per crypt_all()
pass xfer: 396.200ms* (exceeds 300ms)
Local worksize (LWS) 32, global worksize (GWS) 640
DONE
Speed for cost 1 (iteration count) of 5000
Raw:	800 c/s real, 21333 c/s virtual


real	0m11.766s
user	0m3.108s
sys	0m0.388s
```

**Comment by magnumripper** [comment]
Strange. I can't really see what actually happened there.

**Comment by frank-dittrich** [comment]
To you have a patch I can test, to provide more detailed information?

**Comment by magnumripper** [comment]
Nah, Einmal ist keinmal. The change I did is a total no-op except for this strange case.

**Comment by frank-dittrich** [comment]
I though you wanted to find out how this strange case could happen.

**Comment by magnumripper** [comment]
You already provided all data I can think of (values of involved variables, which was great!)... I can't see how it could even end up like that but I don't have any time for this unless we see more problems.
