### ISSUE TITLE
ASan error in vdi format 

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1956]
```
$ ./john --test=0 --format=vdi
Testing: vdi, VirtualBox-VDI AES_XTS [PBKDF2-SHA256 128/128 AVX 4x + AES_XTS]... =================================================================
==9361==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000001d163a0 at pc 0x000000575d45 bp 0x7ffc2c6cb010 sp 0x7ffc2c6cb008
WRITE of size 1 at 0x000001d163a0 thread T0
    #0 0x575d44 in hex_to_raw /home/fd/git/JtR/src/base64_convert.c:247:2
    #1 0x5749ac in base64_convert /home/fd/git/JtR/src/base64_convert.c:802:6
    #2 0x7f5b21 in binary /home/fd/git/JtR/src/vdi_fmt_plug.c:353:2
    #3 0x844f27 in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:850:12
    #4 0x846663 in ldr_init_test_db /home/fd/git/JtR/src/loader.c:1094:3
    #5 0x80efe3 in benchmark_all /home/fd/git/JtR/src/bench.c:684:13
    #6 0x834905 in john_run /home/fd/git/JtR/src/john.c:1585:17
    #7 0x831ebf in main /home/fd/git/JtR/src/john.c:1970:2
    #8 0x7f3d10a776ff in __libc_start_main (/lib64/libc.so.6+0x206ff)
    #9 0x4dbc88 in _start (/home/fd/git/JtR/run/john+0x4dbc88)

0x000001d163a0 is located 32 bytes to the left of global variable 'cur_salt' defined in 'vms_fmt_plug.c:182:30' (0x1d163c0) of size 8
0x000001d163a0 is located 0 bytes to the right of global variable 'full' defined in 'vdi_fmt_plug.c:349:22' (0x1d16380) of size 32
SUMMARY: AddressSanitizer: global-buffer-overflow /home/fd/git/JtR/src/base64_convert.c:247 hex_to_raw
Shadow bytes around the buggy address:
  0x00008039ac20: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008039ac30: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008039ac40: f9 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039ac50: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x00008039ac60: 00 00 00 00 00 00 00 00 00 00 00 04 f9 f9 f9 f9
=>0x00008039ac70: 00 00 00 00[f9]f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039ac80: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039ac90: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x00008039aca0: 00 00 00 00 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x00008039acb0: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039acc0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
==9361==ABORTING
```

```
$ ./john --list=build-info 
Version: 1.8.0.6-jumbo-1-1768-gd157e31
Build: linux-gnu 64-bit AVX-ac ASan
SIMD: AVX, interleaving: MD4:4 MD5:5 SHA1:2 SHA256:1 SHA512:1
$JOHN is ./
Format interface version: 13
Max. number of reported tunable costs: 3
Rec file version: REC4
Charset file version: CHR3
CHARSET_MIN: 1 (0x01)
CHARSET_MAX: 255 (0xff)
CHARSET_LENGTH: 24
SALT_HASH_SIZE: 1048576
Max. Markov mode level: 400
Max. Markov mode password length: 30
clang version: 3.5.0 (tags/RELEASE_350/final) (gcc 4.3.0 compatibility)
GNU libc version: 2.21 (loaded: 2.21)
Crypto library: OpenSSL
OpenSSL library version: 0100010bf
OpenSSL 1.0.1k-fips 8 Jan 2015
GMP library version: 6.0.0
File locking: fcntl()
fseek(): fseek
ftell(): ftell
fopen(): fopen
memmem(): System's
Built with these debugging options
	ASan (Address Sanitizer debugging)

```

Since one of the recent commits changed vdi, I just reproduced with the latest commit:
```
 ./john --test=0 --format=vdi
Testing: vdi, VirtualBox-VDI AES_XTS [PBKDF2-SHA256 128/128 AVX 4x + AES_XTS]... =================================================================
==9595==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000001d153a0 at pc 0x000000575d45 bp 0x7ffd28577310 sp 0x7ffd28577308
WRITE of size 1 at 0x000001d153a0 thread T0
    #0 0x575d44 in hex_to_raw /home/fd/git/JtR/src/base64_convert.c:247:2
    #1 0x5749ac in base64_convert /home/fd/git/JtR/src/base64_convert.c:802:6
    #2 0x7f5b21 in binary /home/fd/git/JtR/src/vdi_fmt_plug.c:358:2
    #3 0x844f27 in ldr_load_pw_line /home/fd/git/JtR/src/loader.c:850:12
    #4 0x846663 in ldr_init_test_db /home/fd/git/JtR/src/loader.c:1094:3
    #5 0x80efe3 in benchmark_all /home/fd/git/JtR/src/bench.c:684:13
    #6 0x834905 in john_run /home/fd/git/JtR/src/john.c:1585:17
    #7 0x831ebf in main /home/fd/git/JtR/src/john.c:1970:2
    #8 0x7fe18fab16ff in __libc_start_main (/lib64/libc.so.6+0x206ff)
    #9 0x4dbc88 in _start (/home/fd/git/JtR/run/john+0x4dbc88)

0x000001d153a0 is located 32 bytes to the left of global variable 'cur_salt' defined in 'vms_fmt_plug.c:182:30' (0x1d153c0) of size 8
0x000001d153a0 is located 0 bytes to the right of global variable 'full' defined in 'vdi_fmt_plug.c:351:22' (0x1d15380) of size 32
SUMMARY: AddressSanitizer: global-buffer-overflow /home/fd/git/JtR/src/base64_convert.c:247 hex_to_raw
Shadow bytes around the buggy address:
  0x00008039aa20: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008039aa30: f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x00008039aa40: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039aa50: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x00008039aa60: 00 00 00 00 00 00 00 00 00 00 00 04 f9 f9 f9 f9
=>0x00008039aa70: 00 00 00 00[f9]f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039aa80: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039aa90: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x00008039aaa0: 00 00 00 00 f9 f9 f9 f9 01 f9 f9 f9 f9 f9 f9 f9
  0x00008039aab0: 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9
  0x00008039aac0: 00 f9 f9 f9 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  ASan internal:           fe
```

**Comment by magnumripper** [comment]
Looks pretty much like a variant of #1943.

**Comment by jfoug** [comment]
9d7c057  I was null terminating a raw buffer !?!?!
