### ISSUE TITLE
nvopencl crashes inside clGetPlatformInfo on x86_64 cygwin

### ISSUE THREAD

**Issue by shrikus** [magnumripper/JohnTheRipper#1971]
```
export NVCC="/usr/local/cuda-7.5/bin/nvcc.exe"; export CFLAGS="-DOCL_DEBUG -g -I/usr/local/amdapp/include -L/usr/local/amdapp/lib64"; export CPPFLAGS=${CFLAGS}; export LDFLAGS="-L/usr/local/amdapp/lib64"; ./configure
```

```
Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 AVX, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. cygwin
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Fuzzing test ............................... no
Experimental code .......................... no
OpenMPI support (default disabled) ......... no
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
CUDA support (default disabled by OpenCL) .. no
OpenCL support ............................. yes
Generic crypt(3) format .................... no
Rexgen (extra cracking mode) ............... no
GMP (PRINCE mode and faster SRP formats) ... no
PCAP (vncpcap2john and SIPdump) ............ no
Z (pkzip format, gpg2john) ................. yes
BZ2 (gpg2john extra decompression logic) ... no
128-bit integer (faster PRINCE mode) ....... yes
Memory map (share/page large files) ........ yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ........... disabled
AddressSanitizer ("ASan") .................. disabled
UndefinedBehaviorSanitizer ("UbSan") ....... disabled

Install missing libraries to get any needed features that were omitted.
```

```
(gdb) run --list=opencl-devices
Starting program: /home/sergey/JohnTheRipper/run/john.exe --list=opencl-devices
[New Thread 501804.0x7ad9c]
[New Thread 501804.0x7ade0]
[New Thread 501804.0x7a828]
[New Thread 501804.0x7adac]
[New Thread 501804.0x7ad64]
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
[New Thread 501804.0x7ad4c]
[New Thread 501804.0x7ad68]
[New Thread 501804.0x7ad74]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffb8fe96194 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
(gdb) bt
#0  0x00007ffb8fe96194 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#1  0x00007ffb8fe3da0f in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#2  0x00007ffb8fe3cda6 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#3  0x00007ffb8fd43c74 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#4  0x00007ffb8fd4212d in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#5  0x00007ffb8fa2cd70 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#6  0x00007ffb8fa2c363 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#7  0x00007ffbb00613e1 in clCreateContext () from /cygdrive/c/Windows/SYSTEM32/OpenCL.dll
#8  0x00000001007a88d9 in start_opencl_device (sequential_id=0, err_type=0xffffc4e8) at common-opencl.c:536
#9  0x00000001007a8c00 in add_device_to_list (sequential_id=0) at common-opencl.c:585
#10 0x00000001007a8fe5 in build_device_list (device_list=0xffffc570) at common-opencl.c:640
#11 0x00000001007a92fd in opencl_preinit () at common-opencl.c:712
#12 0x00000001007903b9 in listconf_parse_late () at listconf.c:418
#13 0x00000001007672e5 in john_init (name=0x60003a81f "john", argc=2, argv=0xffffcc00) at john.c:1517
#14 0x00000001007683c2 in main (argc=2, argv=0xffffcc00) at john.c:1960
```

```
(gdb) run --test --format=raw-md5-opencl
Starting program: /home/sergey/JohnTheRipper/run/john.exe --test --format=raw-md5-opencl
[New Thread 503780.0x7ac0c]
[New Thread 503780.0x7ac3c]
[New Thread 503780.0x7ac08]
[New Thread 503780.0x7ac50]
[New Thread 503780.0x7abd0]
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
[New Thread 503780.0x7a61c]
[New Thread 503780.0x7acb0]
[New Thread 503780.0x7aed0]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffb8fe96194 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
(gdb) bt
#0  0x00007ffb8fe96194 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#1  0x00007ffb8fe3da0f in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#2  0x00007ffb8fe3cda6 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#3  0x00007ffb8fd43c74 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#4  0x00007ffb8fd4212d in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#5  0x00007ffb8fa2cd70 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#6  0x00007ffb8fa2c363 in nvopencl!clGetPlatformInfo () from /cygdrive/c/Windows/System32/nvopencl.dll
#7  0x00007ffbb00613e1 in clCreateContext () from /cygdrive/c/Windows/SYSTEM32/OpenCL.dll
#8  0x00000001007a88d9 in start_opencl_device (sequential_id=0, err_type=0xffffbb88) at common-opencl.c:536
#9  0x00000001007a8c00 in add_device_to_list (sequential_id=0) at common-opencl.c:585
#10 0x00000001007a8fe5 in build_device_list (device_list=0xffffbc10) at common-opencl.c:640
#11 0x00000001007a92fd in opencl_preinit () at common-opencl.c:712
#12 0x00000001007ae480 in opencl_prepare_dev (sequential_id=-1) at common-opencl.c:1894
#13 0x0000000100692e0d in init (_self=0x100917360 <fmt_opencl_rawMD5>) at opencl_rawmd5_fmt_plug.c:247
#14 0x000000010075ab6d in fmt_init (format=0x100917360 <fmt_opencl_rawMD5>) at formats.c:83
#15 0x000000010074e949 in benchmark_all () at bench.c:594
#16 0x00000001007675ad in john_run () at john.c:1587
#17 0x0000000100768432 in main (argc=3, argv=0xffffcbe0) at john.c:1973
```
```
hellocl example working as well...

$ gcc hellocl.c -o hellocl.exe -I/usr/local/amdapp/include -L/usr/local/amdapp/lib64 -lOpenCL
$ ./hellocl.exe
Uryyb, Jbeyq!
Hello, World!
```

```
$ ./clinfo.exe
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.2 CUDA 8.0.5
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     GeForce GTX 660
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.2 CUDA
  Driver Version                                  361.43
  Device OpenCL C Version                         OpenCL C 1.2
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Topology (NV)                            PCI-E, 01:00.0
  Max compute units                               5
  Max clock frequency                             1058MHz
  Compute Capability (NV)                         3.0
  Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x64
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes
    char                                                 1 / 1
    short                                                1 / 1
    int                                                  1 / 1
    long                                                 1 / 1
    half                                                 0 / 0        (n/a)
    float                                                1 / 1
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              2147483648 (2GiB)
  Error Correction support                        No
  Max memory allocation                           536870912 (512MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       4096 bits (512 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        81920
  Global Memory cache line                        128 bytes
  Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             4096x4096x4096 pixels
    Max number of read image args                 256
    Max number of write image args                16
  Local memory type                               Local
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     9
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1000ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  1
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform
```

**Comment by claudioandre** [comment]
Could you please, try this patch

```
diff --git a/src/common-opencl.c b/src/common-opencl.c
index ef98cdc..7c0735e 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -676,6 +676,11 @@ void opencl_preinit(void)
                        queue[i] = NULL;
                }
                start_opencl_environment();
+printf("==> V: %d %d\n", get_number_of_available_platforms(), get_number_of_available_devices());              
+               if (get_number_of_available_devices() == 0) {
+                       fprintf(stderr, "No OpenCL devices found\n");
+                       error();
+               }
```

**Comment by shrikus** [comment]
```
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
OpenCL platform 1: AMD Accelerated Parallel Processing, 1 device(s).
==> V: 2 2
Segmentation fault (core dumped)
```

**Comment by claudioandre** [comment]
Well:
- OpenCL library think is has 2 working platforms. But
- one internal call of clGetPlatformInfo() is failing (the library calls clGetPlatformInfo() not JtR)
- so, what is failing? I mean which parameters?.
 
That said (if you are in the mood), please do some tests in order to find which (internal) call if failing:

```
diff --git a/src/common-opencl.c b/src/common-opencl.c
index ef98cdc..496d1aa 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -491,6 +491,7 @@ static int start_opencl_device(int sequential_id, int *err_type)
 {
        cl_context_properties properties[3];
        char opencl_data[LOG_SIZE];
+       int ret;
 
        // Get the detailed information about the device.
        opencl_get_dev_info(sequential_id);
@@ -531,7 +532,12 @@ static int start_opencl_device(int sequential_id, int *err_type)
        properties[1] = (cl_context_properties)
                        platforms[get_platform_id(sequential_id)].platform;
        properties[2] = 0;
-
+//----
+printf("==> V: %d %d %p %p %s\n", sequential_id, get_platform_id(sequential_id), platforms[get_platform_id(sequential_id)].platform, devices[sequential_id], opencl_data);
+       ret = clGetPlatformInfo(platforms[get_platform_id(sequential_id)].platform,
+               CL_PLATFORM_NAME, sizeof(opencl_data), opencl_data, NULL);
+printf("==> W: %d, %s\n", ret, opencl_data);
+//----
        // Setup context and queue
        context[sequential_id] = clCreateContext(properties, 1,
                                 &devices[sequential_id], NULL, NULL, &ret_code);
@@ -676,6 +682,9 @@ void opencl_preinit(void)
                        queue[i] = NULL;
                }
                start_opencl_environment();
+//----
+printf("==> U: %d %d\n", get_number_of_available_platforms(), get_number_of_available_devices());
+//----
                {
                        struct list_entry *current;
 
```

**Comment by claudioandre** [comment]
You can also change the kind of info required (replace CL_PLATFORM_NAME with the options below):

CL_PLATFORM_PROFILE
CL_PLATFORM_VERSION
CL_PLATFORM_NAME
CL_PLATFORM_VENDOR
CL_PLATFORM_EXTENSIONS

**Comment by shrikus** [comment]
```
==> U: 2 2
==> V: 0 0 0x329e20 0x32a190 GeForce GTX 660

CL_PLATFORM_NAME        ==> W: 0, NVIDIA CUDA
CL_PLATFORM_PROFILE     ==> W: 0, FULL_PROFILE
CL_PLATFORM_VERSION     ==> W: 0, OpenCL 1.2 CUDA 8.0.5
CL_PLATFORM_VENDOR      ==> W: 0, NVIDIA Corporation
CL_PLATFORM_EXTENSIONS  ==> W: 0, cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts
```

I also dumped device info:

```
	ret = clGetDeviceInfo(devices[sequential_id], CL_DEVICE_NAME, sizeof(opencl_data), opencl_data, NULL );
	printf("==> X: %d, %s\n", ret, opencl_data);

CL_DEVICE_NAME       ==> X: 0, GeForce GTX 660
CL_DEVICE_EXTENSIONS ==> X: 0, cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts
CL_DEVICE_PROFILE    ==> X: 0, FULL_PROFILE
CL_DEVICE_VENDOR     ==> X: 0, NVIDIA Corporation
CL_DEVICE_VERSION    ==> X: 0, OpenCL 1.2 CUDA
CL_DRIVER_VERSION    ==> X: 0, 361.43
```

Parameters looks fine, but it still crashing inside clCreateContext().

**Comment by claudioandre** [comment]
Unfortunately, it seems to be a bug in your environment. Anyway, you can try to see if you can find a way to use it (since it works somehow in other tools). 
* Change clCreateContext() parameters **and** try to specify -dev=0 or -dev=1.

```
diff --git a/src/common-opencl.c b/src/common-opencl.c
index ef98cdc..695fc7e 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -533,8 +533,12 @@ static int start_opencl_device(int sequential_id, int *err_type)
        properties[2] = 0;
 
        // Setup context and queue
-       context[sequential_id] = clCreateContext(properties, 1,
+       //context[sequential_id] = clCreateContext(NULL, 1,
+       //                         NULL, NULL, NULL, &ret_code);
+
+       context[sequential_id] = clCreateContext(NULL, 1,
                                 &devices[sequential_id], NULL, NULL, &ret_code);
+       printf("V: %d %d \n", ret_code, (ret_code == CL_INVALID_VALUE));
        if (ret_code != CL_SUCCESS) {
 #ifdef OCL_DEBUG
                fprintf(stderr, "Error creating context for device %d "

```

**Comment by claudioandre** [comment]
Maybe you can play with the *pfn_notify (4th parameter), but a ```SIGSEGV``` suggests it might wont help either.

\* A callback function that can be registered by the application. This callback function will be used by the OpenCL implementation to report information on errors that occur in this context.

**Comment by claudioandre** [comment]
Using the patch below **and** -dev=0 or -dev=1 you can see if JtR can get the GPU info/details 
```../run/john --list=opencl-devices -dev=1```. My guess is that it will work fine:

```
diff --git a/src/common-opencl.c b/src/common-opencl.c
index ef98cdc..be96191 100644
--- a/src/common-opencl.c
+++ b/src/common-opencl.c
@@ -491,7 +491,7 @@ static int start_opencl_device(int sequential_id, int *err_type)
 {
        cl_context_properties properties[3];
        char opencl_data[LOG_SIZE];
-
+       return 1;
        // Get the detailed information about the device.
        opencl_get_dev_info(sequential_id);
```

**Comment by shrikus** [comment]
yeah with 'return 1' patch it getting info/details for both devices. 
without return it crashes with '-dev=0' option.

```
$ ../run/john.exe --list=opencl-devices -dev=0
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
OpenCL platform 1: AMD Accelerated Parallel Processing, 1 device(s).
==> U: 2 2
Platform #0 name: NVIDIA CUDA, version: OpenCL 1.2 CUDA 8.0.5
    Device #0 (0) name:     GeForce GTX 660
    Device vendor:          NVIDIA Corporation
    Device type:            GPU (LE)
    Device version:         OpenCL 1.2 CUDA
Driver: 938, 2 -> 12.8 , (null)
Driver: 1084, 4 -> 13.1 , (null)
Driver: 1124, 2 -> 13.4 , (null)
Driver: 1214, 3 -> 13.6beta , (null)
Driver: 1311, 2 -> 13.11beta-1 , (null)
Driver: 1348, 5 -> 13.12 , (null)
Driver: 1445, 5 -> 14.4(Mantle) , (null)
Driver: 1526, 3 -> 14.6beta(Mantle) , (null)
Driver: 1573, 4 -> 14.9(Mantle) , VGLS
Driver: 1642, 5 -> 14.12(Omega) , VGLS
Driver: 1702, 3 -> 15.5beta , T
Driver: 1729, 3 -> 15.5 , (null)
Driver: 1800, 5 -> 15.7 , VG*R
Driver: 1800, 8 -> 15.7.1 , VGWR
Driver: 1800, 11 -> 15.9 , VGLS
Driver: 1912, 5 -> 15.11 , (null)
    Driver version:         361.43 [recommended]
    Native vector widths:   char 1, short 1, int 1, long 1
    Preferred vector width: char 1, short 1, int 1, long 1
    Global Memory:          2.0 GB
    Global Memory Cache:    80.0 KB
    Local Memory:           48.0 KB (Local)
    Max memory alloc. size: 512.5 MB
    Max clock (MHz):        1058
    Profiling timer res.:   1000 ns
    Max Work Group Size:    1024
    Parallel compute cores: 5
    Stream processors:      960  (5 x 192)
    Speed index:            1015680
    Warp size:              32
    Max. GPRs/work-group:   65536
    Kernel exec. timeout:   yes
    PCI device topology:
```

```
$ ../run/john.exe --list=opencl-devices -dev=1
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
OpenCL platform 1: AMD Accelerated Parallel Processing, 1 device(s).
==> U: 2 2
Platform #1 name: AMD Accelerated Parallel Processing, version: OpenCL 2.0 AMD-APP (1800.8)
    Device #0 (1) name:     Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    Device vendor:          GenuineIntel
    Device type:            CPU (LE)
    Device version:         OpenCL 1.2 AMD-APP (1800.8)
Driver: 938, 2 -> 12.8 , (null)
Driver: 1084, 4 -> 13.1 , (null)
Driver: 1124, 2 -> 13.4 , (null)
Driver: 1214, 3 -> 13.6beta , (null)
Driver: 1311, 2 -> 13.11beta-1 , (null)
Driver: 1348, 5 -> 13.12 , (null)
Driver: 1445, 5 -> 14.4(Mantle) , (null)
Driver: 1526, 3 -> 14.6beta(Mantle) , (null)
Driver: 1573, 4 -> 14.9(Mantle) , VGLS
Driver: 1642, 5 -> 14.12(Omega) , VGLS
Driver: 1702, 3 -> 15.5beta , T
Driver: 1729, 3 -> 15.5 , (null)
Driver: 1800, 5 -> 15.7 , VG*R
Driver: 1800, 8 -> 15.7.1 , VGWR
Driver: 1800, 11 -> 15.9 , VGLS
Driver: 1912, 5 -> 15.11 , (null)
Driver: 346, 0 ->  , N*R
Driver: 319, 0 ->  , N*S
Driver: 0, 0 ->  , (null)
    Driver version:         1800.8 (sse2,avx)
    Native vector widths:   char 16, short 8, int 4, long 2
    Preferred vector width: char 16, short 8, int 4, long 2
    Global Memory:          15.0 GB
    Global Memory Cache:    32.0 KB
    Local Memory:           32.0 KB (Global)
    Max memory alloc. size: 3.0 GB
    Max clock (MHz):        3400
    Profiling timer res.:   301 ns
    Max Work Group Size:    1024
    Parallel compute cores: 4
    Speed index:            54400
    PCI device topology:
```

i removed return and checked it again with --dev=1 (CPU), and it working fine:

```
$ ../run/john.exe --test -dev=1 --format=raw-md5-opencl
OpenCL platform 0: NVIDIA CUDA, 1 device(s).
OpenCL platform 1: AMD Accelerated Parallel Processing, 1 device(s).
==> U: 2 2
V: 0 0
  Device 1:        Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
Device 1: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
Benchmarking: Raw-MD5-opencl [MD5 OpenCL]... DONE
Raw:    10134K c/s real, 3447K c/s virtual
```

**Comment by shrikus** [comment]
Just tried to use pfn_notify callback but unfortunely it's not helped.
