### ISSUE TITLE
ASan error in Raw-SHA1-AxCrypt (linux-gnu 64-bit AVX2-ac OMP ASan build)

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#2042]
```
(bleeding-jumbo)run $ ./john --test --format=Raw-SHA1-AxCrypt 
NOTE: This is a debug build, speed will be lower than normal
Benchmarking: Raw-SHA1-AxCrypt [SHA1 256/256 AVX2 8x]... =================================================================
==25894==ERROR: AddressSanitizer: unknown-crash on address 0x60300000ddb4 at pc 0x00000084ad8c bp 0x7fffb6c8bdf0 sp 0x7fffb6c8bde0
READ of size 20 at 0x60300000ddb4 thread T0
    #0 0x84ad8b in source /home/fd/git/JtR/src/rawSHA1_fmt_plug.c:287
    #1 0x8d0cb0 in fmt_self_test_body /home/fd/git/JtR/src/formats.c:733
    #2 0x8d277e in fmt_self_test /home/fd/git/JtR/src/formats.c:1620
    #3 0x8b51d7 in benchmark_format /home/fd/git/JtR/src/bench.c:364
    #4 0x8b6de2 in benchmark_all /home/fd/git/JtR/src/bench.c:803
    #5 0x8e0d4f in john_run /home/fd/git/JtR/src/john.c:1587
    #6 0x8e2513 in main /home/fd/git/JtR/src/john.c:1973
    #7 0x7f74d293a6ff in __libc_start_main (/lib64/libc.so.6+0x206ff)
    #8 0x407778 in _start (/home/fd/git/JtR/run/john+0x407778)

0x60300000ddc7 is located 0 bytes to the right of 23-byte region [0x60300000ddb0,0x60300000ddc7)
allocated by thread T0 here:
    #0 0x7f74d481396a in malloc (/lib64/libasan.so.2+0x9896a)
    #1 0x8ffef1 in mem_alloc_func /home/fd/git/JtR/src/memory.c:91
    #2 0x8cbf57 in alloc_binary /home/fd/git/JtR/src/formats.c:1574
    #3 0x8d2672 in fmt_self_test /home/fd/git/JtR/src/formats.c:1611
    #4 0x8b51d7 in benchmark_format /home/fd/git/JtR/src/bench.c:364
    #5 0x8b6de2 in benchmark_all /home/fd/git/JtR/src/bench.c:803
    #6 0x8e0d4f in john_run /home/fd/git/JtR/src/john.c:1587
    #7 0x8e2513 in main /home/fd/git/JtR/src/john.c:1973
    #8 0x7f74d293a6ff in __libc_start_main (/lib64/libc.so.6+0x206ff)

SUMMARY: AddressSanitizer: unknown-crash /home/fd/git/JtR/src/rawSHA1_fmt_plug.c:287 source
Shadow bytes around the buggy address:
  0x0c067fff9b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fff9ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c067fff9bb0: fa fa fa fa fa fa[00]00 07 fa fa fa 00 00 00 00
  0x0c067fff9bc0: fa fa fd fd fd fa fa fa 00 00 00 00 fa fa fd fd
  0x0c067fff9bd0: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x0c067fff9be0: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fd
  0x0c067fff9bf0: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c067fff9c00: fd fd fa fa fd fd fd fa fa fa fd fd fd fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==25894==ABORTING
```

**Comment by claudioandre** [comment]
I couldn't reproduce on well

```
$ ../run/john                                 
John the Ripper 1.8.0-jumbo-1-4606-g84e701c OMP ASan [linux-gnu 64-bit AVX2-ac]
Copyright (c) 1996-2016 by Solar Designer and others
```
```
$ ./john --test --format=Raw-SHA1-AxCrypt
NOTE: This is a debug build, speed will be lower than normal
Benchmarking: Raw-SHA1-AxCrypt [SHA1 256/256 AVX2 8x]... DONE
Raw:	14650K c/s real, 14650K c/s virtual

```
But maybe (line 287 is a memcpy)?
```
diff --git a/src/rawSHA1_fmt_plug.c b/src/rawSHA1_fmt_plug.c
index 82e983f..340eb06 100644
--- a/src/rawSHA1_fmt_plug.c
+++ b/src/rawSHA1_fmt_plug.c
@@ -278,7 +278,7 @@ static void *get_binary(char *ciphertext)
 
 static char *source(char *source, void *binary)
 {
-       ARCH_WORD_32 hash[DIGEST_SIZE / 4];
+       ARCH_WORD_32 hash[DIGEST_SIZE / sizeof(ARCH_WORD_32)];
        char hex[2 * DIGEST_SIZE + 1];
        char *fields[10] = { 0 };
        char *p;
```

**Comment by jfoug** [comment]
The failure was a 20 byte 'read' from a 16 byte source.
