### ISSUE TITLE
Crash in QNX hash detection due to NULL pointer dereference

### ISSUE THREAD

**Issue by hdm** [magnumripper/JohnTheRipper#2165]
Running HEAD bleeding-jumbo (2d5a58d425d5f914beee7618cb7677121444c197) and hitting a crash testing against the MySpace dump (0x prefix removed from the SHA1s).

Looks like a NULL ptr dereference in the qnx hash detection:
```
(gdb) r Myspace.com.txt.jtr 
Starting program: /home/work/tools/JohnTheRipper/run/john Myspace.com.txt.jtr
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "Raw-SHA1-AxCrypt"
Use the "--format=Raw-SHA1-AxCrypt" option to force loading these as that type instead
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "Raw-SHA1-Linkedin"
Use the "--format=Raw-SHA1-Linkedin" option to force loading these as that type instead
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "Raw-SHA"
Use the "--format=Raw-SHA" option to force loading these as that type instead
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "ripemd-160"
Use the "--format=ripemd-160" option to force loading these as that type instead
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "Raw-SHA1-ng"
Use the "--format=Raw-SHA1-ng" option to force loading these as that type instead
Warning: detected hash type "Raw-SHA1", but the string is also recognized as "Raw-SHA1-opencl"
Use the "--format=Raw-SHA1-opencl" option to force loading these as that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "pix-md5"
Use the "--format=pix-md5" option to force loading hashes of that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "descrypt"
Use the "--format=descrypt" option to force loading hashes of that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "tripcode"
Use the "--format=tripcode" option to force loading hashes of that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "descrypt-opencl"
Use the "--format=descrypt-opencl" option to force loading hashes of that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "HMAC-SHA256"
Use the "--format=HMAC-SHA256" option to force loading hashes of that type instead
Warning: only loading hashes of type "Raw-SHA1", but also saw type "HMAC-SHA512"
Use the "--format=HMAC-SHA512" option to force loading hashes of that type instead

Program received signal SIGSEGV, Segmentation fault.

valid (ciphertext=<optimized out>, self=<optimized out>) at qnx_common.h:41
41		if (*ct == 'm') len = 32;

(gdb) x/i *ct
Cannot access memory at address 0x0
...
#0  valid (ciphertext=<optimized out>, self=<optimized out>) at qnx_common.h:41
#1  0x00000000006e0fde in ldr_split_line (login=login@entry=0x7fffffffdd50, ciphertext=ciphertext@entry=0x7fffffffdd58, gecos=gecos@entry=0x7fffffffdd60, 
    home=home@entry=0x7fffffffdd68, uid=uid@entry=0x7fffffffdd70, source=source@entry=0x0, format=format@entry=0xd6b0b8 <database+120>, db_opts=0x119e5e8, 
    line=0x0) at loader.c:759
#2  0x00000000006e182b in ldr_load_pw_line (db=0xd6b040 <database>, line=<optimized out>) at loader.c:924
#3  0x00000000006dfdd2 in read_file (db=0xd6b040 <database>, name=0xe51080 "Myspace.com.txt.jtr", flags=<optimized out>, 
    process_line=0x6e17e0 <ldr_load_pw_line>) at loader.c:228
#4  0x00000000006ddcee in john_load () at john.c:1170
#5  0x00000000006de740 in john_init (name=0x7fffffffe80b "john", argc=2, argv=0x7fffffffe4f8) at john.c:1497
#6  0x00000000006df622 in main (argc=2, argv=0x7fffffffe4f8) at john.c:1959
(gdb) 
```

**Comment by frank-dittrich** [comment]
As expected, this triggers the segfault:
```
(bleeding-jumbo)run $ cat testqnx 
:@
(bleeding-jumbo)run $ ./john testqnx 
Segmentation fault (core dumped)
(bleeding-jumbo)run $ ./john testqnx --format=qnx 
Segmentation fault (core dumped)
(bleeding-jumbo)run $ 
```

A dummy hash file with just the '@' and no colon doesn't trigger the segfault.

**Comment by hdm** [comment]
@frank-dittrich thanks!
