### ISSUE TITLE
oldoffice-opencl segfaults if run with --skip-self-test

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#2256]
I recall some more OpenCL format(s) with GPU-side mask may have the same problem. Not the end of the world, the worst consequence might be it prohibits use of the test suite as-is.

**Comment by frank-dittrich** [comment]
For the test suite, you can use `-passthru=--skip-self-tests` to work around this problem.

**Comment by magnumripper** [comment]
It's the other way round. TS does that.

**Comment by frank-dittrich** [comment]
While most of the other segfaults afl found so far result in the same two back traces I already posted, this one 
```
d2ffffffffcb8dd24c
```
will result in
```
ASAN:SIGSEGV
=================================================================
==3623==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f35f001ad84 bp 0x7ffc609a1d70 sp 0x7ffc60981cc8 T0)
    #0 0x7f35f001ad83 in strlen (/lib/x86_64-linux-gnu/libc.so.6+0x8ad83)
    #1 0x7f35effff5db in _IO_puts (/lib/x86_64-linux-gnu/libc.so.6+0x6f5db)
    #2 0x8429d6 in Symmetrically_Encrypted_and_MDC_Packet /home/ubuntuadm/git/JtR/src/gpg2john.c:1071
    #3 0x8442b2 in parse_packet /home/ubuntuadm/git/JtR/src/gpg2john.c:1531
    #4 0x844802 in gpg2john /home/ubuntuadm/git/JtR/src/gpg2john.c:360
    #5 0x7d5a3d in main /home/ubuntuadm/git/JtR/src/john.c:1933
    #6 0x7f35effb082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #7 0x4061f8 in _start (/home/ubuntuadm/git/JtR/run/john+0x4061f8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 strlen
```
(after converting from hex to raw)
