### ISSUE TITLE
descrypt-opencl per-salt kernels optimization 4096 limit is not working properly

### ISSUE THREAD

**Issue by claudioandre** [magnumripper/JohnTheRipper#2660]
I created a test case that has 4096 different salts and more than 10k hashes.

```
#0  0x000000000079dc64 in create_tables (htype=<value optimized out>, loaded_hashes_ptr=<value optimized out>, 
    num_ld_hashes=<value optimized out>, offset_table_ptr=0x7fffffffa090, offset_table_sz_ptr=0x7fffffffa098, 
    hash_table_sz_ptr=0x7fffffffa09c, verb=0) at bt.c:474
#1  create_perfect_hash_table (htype=<value optimized out>, loaded_hashes_ptr=<value optimized out>, num_ld_hashes=<value optimized out>, 
    offset_table_ptr=0x7fffffffa090, offset_table_sz_ptr=0x7fffffffa098, hash_table_sz_ptr=0x7fffffffa09c, verb=0) at bt.c:696
#2  0x0000000000611192 in fill_buffer (salt=<value optimized out>, max_uncracked_hashes=<value optimized out>, max_hash_table_size=0xd1eb04)
    at opencl_DES_bs_plug.c:224
#3  0x0000000000611752 in build_tables (db=<value optimized out>) at opencl_DES_bs_plug.c:423
#4  0x000000000060ca3d in reset (db=0xd64600) at opencl_DES_bs_h_plug.c:667
#5  0x000000000074aee5 in john_run () at john.c:1710
#6  0x000000000074b785 in main (argc=8, argv=0x7fffffffe398) at john.c:1996
```

See #2655.

**Comment by solardiz** [comment]
Looks unrealistic we'll make relevant changes and properly re-test them on all platforms before the release. Changed milestone.
