### ISSUE TITLE
Crashes in shared OpenMP auto-tuning code

### ISSUE THREAD

**Issue by kholia** [magnumripper/JohnTheRipper#3100]
This is a real POWER8E box.

```
$ git rev-parse HEAD
13fe1ba778add08d49c56bdfbbb00b5e91c7d245

$ OMP_NUM_THREADS=1 gdb --args ../run/john --test=0
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
(gdb) r

Testing: descrypt, traditional crypt(3) [DES 128/128 AltiVec]... PASS
...
Testing: agilekeychain, 1Password Agile Keychain [PBKDF2-SHA1 AES 128/128 AltiVec 4x]... 
Program received signal SIGSEGV, Segmentation fault.
0x00003fffb779fb64 in __strcmp_power8 () from /lib64/libc.so.6
(gdb) bt
#0  0x00003fffb779fb64 in __strcmp_power8 () from /lib64/libc.so.6
#1  0x000000001005b888 in omp_autotune_run (db=0x10adf190) at omp_autotune.c:121
#2  0x00000000102e7378 in fmt_self_test_body (full_lvl=-1, db=0x10adf190, ...) at formats.c:502
#3  fmt_self_test (format=0x1051ba40 <fmt_agile_keychain>, db=0x10adf190) at formats.c:1690
#4  0x0000000000000000 in ?? ()

(gdb) x/40i $pc-32
   0x3fffb779fb44 <__strcmp_power8+4>:  addi    r2,r2,-25152
   0x3fffb779fb48 <__strcmp_power8+8>:  li      r0,0
   0x3fffb779fb4c <__strcmp_power8+12>: clrldi  r7,r3,52
   0x3fffb779fb50 <__strcmp_power8+16>: clrldi  r9,r4,52
   0x3fffb779fb54 <__strcmp_power8+20>: cmpldi  cr7,r7,4064
   0x3fffb779fb58 <__strcmp_power8+24>: bgt     cr7,0x3fffb779fc80 <__strcmp_power8+320>
   0x3fffb779fb5c <__strcmp_power8+28>: cmpldi  cr5,r9,4064
   0x3fffb779fb60 <__strcmp_power8+32>: bgt     cr5,0x3fffb779fc80 <__strcmp_power8+320>
=> 0x3fffb779fb64 <__strcmp_power8+36>: ld      r8,0(r3)
   0x3fffb779fb68 <__strcmp_power8+40>: ld      r10,0(r4)
   0x3fffb779fb6c <__strcmp_power8+44>: cmpb    r12,r8,r0
   0x3fffb779fb70 <__strcmp_power8+48>: cmpb    r11,r8,r10
   0x3fffb779fb74 <__strcmp_power8+52>: orc.    r9,r12,r11
   0x3fffb779fb78 <__strcmp_power8+56>: bne     0x3fffb779fc50 <__strcmp_power8+272>

Both r3 and r8 are 0 which is weird.

(gdb) frame 1
#1  0x000000001005b888 in omp_autotune_run (db=0x10adf190) at omp_autotune.c:121
121                 (!strcmp(options.tune, "report") || options.verbosity > VERB_DEFAULT))
(gdb) list
116
117             if (!fmt || omp_scale == 1)
118                     goto cleanup;
119
120             if (john_main_process && bench_running &&
121                 (!strcmp(options.tune, "report") || options.verbosity > VERB_DEFAULT))
122                     fprintf(stderr, "\n");
123
124             scale = 1;
125             omp_autotune_running = 1;
```

I will try to debug this a bit later.

@magnumripper This may need attention from your side.

Update: Continuing the GDB session,

```
(gdb) print options.tune
$6 = 0x0
```

This seems like a standard NULL pointer deference problem.

**Comment by magnumripper** [comment]
DEScrypt shouldn't use auto-tune at all, this is a bug of mine. Will look into it right now

**Comment by magnumripper** [comment]
Oh, it's not DEScrypt. This is a silly bug, will fix.

**Comment by kholia** [comment]
Thanks! This indeed fixes the crashes I was seeing :+1:

**Comment by kholia** [comment]
The test box has 160 cores!

```
$ cat /proc/cpuinfo | tail
processor       : 159
cpu             : POWER8E (raw), altivec supported
clock           : 2094.000000MHz
revision        : 2.1 (pvr 004b 0201)

timebase        : 512000000
platform        : PowerNV
model           : 8247-22L
machine         : PowerNV 8247-22L
firmware        : OPAL v3
```
