### ISSUE TITLE
John segfaults inside autotune

### ISSUE THREAD

**Issue by claudioandre-br** [magnumripper/JohnTheRipper#3788]
I was able to break JtR while trying the play with the contest files. Since people are using OpenWall machines, I can't debug myself. Magnum, please, could you please take a look?

Something like this:
```
-form:sha512crypt-opencl --min-len=0 -max-len=4 -dev:4 --fork=2 --mask=?a ~/SuperList.txt
```

```
#0  0x0000000000814620 in get_binary (ciphertext=<value optimized out>) at sha512crypt_common.h:77
#1  0x0000000000747047 in fill_opencl_device (gws=<value optimized out>, binary=0x7fffffffddc0) at opencl_common.c:1564
#2  0x00000000007476ab in gws_test (gws=1024, rounds=5000, sequential_id=<value optimized out>) at opencl_common.c:1604
#3  0x0000000000747e77 in opencl_find_best_gws (step=0, max_duration=<value optimized out>, sequential_id=3, rounds=5000, 
    have_lws=<value optimized out>) at opencl_common.c:2055
#4  0x00000000008161f6 in find_best_gws (self=0xd08c40, lws_is_power_of_two=0, max_duration=-56, gws_limit=0, rounds=5000)
    at opencl_autotune.h:87
#5  autotune_run_extra (self=0xd08c40, lws_is_power_of_two=0, max_duration=-56, gws_limit=0, rounds=5000) at opencl_autotune.h:189
#6  0x0000000000816d50 in autotune_run (db=<value optimized out>) at opencl_autotune.h:281
#7  reset (db=<value optimized out>) at opencl_sha512crypt_fmt_plug.c:519
#8  0x00000000006e26b0 in fmt_self_test_body (format=0xd08c40, db=0x3f800d0) at formats.c:509
#9  fmt_self_test (format=0xd08c40, db=0x3f800d0) at formats.c:1607
#10 0x00000000006ea06c in john_run () at john.c:1740
#11 0x00000000006eb69d in main (argc=<value optimized out>, argv=<value optimized out>) at john.c:2116
```

See also: #3781.

**Comment by magnumripper** [comment]
Got it. Silly bug, good we found it.
```diff
diff --git a/src/opencl_common.c b/src/opencl_common.c
index 24a679eaa..720aa6b6f 100644
--- a/src/opencl_common.c
+++ b/src/opencl_common.c
@@ -1561,7 +1558,7 @@ static void* fill_opencl_device(size_t gws, void **binary)
                while (s->next && s->cost[0] < db->max_cost[0])
                        s = s->next;
                salt = s->salt;
-               *binary = self->methods.binary(s->list->binary);
+               *binary = s->list->binary;
        } else {
                char *ciphertext;
 
```
